Client library docs
web3-storage/docs pull request #10
Opened 2021-07-09 22:50 UTC by johndmulhausen

Covers the current methods from https://github.com/web3-storage/web3.storage/tree/main/packages/client

TODO: `status()` coverage does not include good details about the response yet as I couldn't find it in the source code.

2021-07-09 22:52 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

### `docs/reference/client-library.md`:
- This phrase is duplicated. You should probably leave only “Store Files”.<!--CategoryID:GRAMMAR, RuleID: PHRASE_REPETITION-->
  ```
  ...irst obtain an API key. # Constructor # Store Files Store files using the pu...
                                             ^^^^^^^^^^^^^^^^^^^^^^^
  ```
- This phrase is duplicated. You should probably leave only “Retrieve Files”.<!--CategoryID:GRAMMAR, RuleID: PHRASE_REPETITION-->
  ```
  ...D of the uploaded CAR file. # Example # Retrieve Files Retrieve files using ...
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ... Which to use?: In the vast majority of cases you will want to use the files...
                                             ^^^^^
  ```
- As an alternative to the over-used intensifier ‘very’, consider replacing this phrase.<!--CategoryID:STYLE, RuleID: EN_WEAK_ADJECTIVE-->
  ```
  ...he exception is when you are retrieving very large files in a Node.js contex...
                                             ^^^^^^^^^^
  ```
- This phrase is duplicated. You should probably leave only “Retrieve metadata”.<!--CategoryID:GRAMMAR, RuleID: PHRASE_REPETITION-->
  ```
  ...onsume UnixFSEntry objects. # Example # Retrieve metadata Retrieve metadata ...
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```

2021-07-12 19:40 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

### `docs/reference/client-library.md`:
- Consider using either the past participle “packed” or the present participle “packing” here.<!--CategoryID:GRAMMAR, RuleID: BEEN_PART_AGREEMENT-->
  ```
  ...he client library will be automatically pack your uploads into a content add...
                                             ^^^^
  ```
- This phrase is duplicated. You should probably leave only “Store Files”.<!--CategoryID:GRAMMAR, RuleID: PHRASE_REPETITION-->
  ```
  ...D to retrieve the file. # Constructor # Store Files Store files using the pu...
                                             ^^^^^^^^^^^^^^^^^^^^^^^
  ```
- This phrase is duplicated. You should probably leave only “Retrieve Files”.<!--CategoryID:GRAMMAR, RuleID: PHRASE_REPETITION-->
  ```
  ...D of the uploaded CAR file. # Example # Retrieve Files Retrieve files using ...
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- This phrase is duplicated. You should probably leave only “Retrieve metadata”.<!--CategoryID:GRAMMAR, RuleID: PHRASE_REPETITION-->
  ```
  ...onsume UnixFSEntry objects. # Example # Retrieve metadata Retrieve metadata ...
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- It appears that a comma is missing here.<!--CategoryID:PUNCTUATION, RuleID: AS_OF_XXX_COMMA-->
  ```
  ... web3.storage network. TODO: As of this writing the structure of the Metadat...
                                             ^^^^^^^
  ```

2021-07-12 19:55 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

### `docs/reference/client-library.md`:
- Consider using either the past participle “packed” or the present participle “packing” here.<!--CategoryID:GRAMMAR, RuleID: BEEN_PART_AGREEMENT-->
  ```
  ...he client library will be automatically pack your uploads into a content add...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- It appears that a comma is missing here.<!--CategoryID:PUNCTUATION, RuleID: AS_OF_XXX_COMMA-->
  ```
  ... web3.storage network. TODO: As of this writing the structure of the Metadat...
                                             ^^^^^^^
  ```

2021-07-12 21:59 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

### `docs/reference/client-library.md`:
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```

2021-07-12 22:37 UTC, olizilla commented on docs/reference/client-library.md
> +The client library will automatically pack your uploads into a content addressible archive (CAR) file for uploading to the web3.storage service, which stores data as blocks prefixed with the content
This is accurate, tho strictly it doesn't put it into a file with a `.car` extention, as by that point it's just dealing with a stream of bytes. 

We could frame this more around the client deriving the content address for your files *before* uploading them so we dont have to trust the service, verifiabilty is an intrinsic part of the process.

2021-07-15 13:32 UTC, johnnymatthews requested changes

2021-07-15 13:32 UTC, johnnymatthews commented on docs/reference/client-library.md
> +description: Integrate web3.storage into your code using a client library for your programming language.
```suggestion
description: Integrate Web3.Storage into your code using a client library for your programming language.
```

2021-07-15 13:32 UTC, johnnymatthews commented on docs/reference/client-library.md
> +description: Integrate web3.storage into your code using a client library for your programming language.
I remember someone saying we should capitalize Web3.Storage.

2021-07-15 13:32 UTC, johnnymatthews commented on docs/reference/client-library.md
> +To use the JavaScript client library for web3.storage, you must first [obtain an API key](../how-tos/regenerate-api-key.md).
```suggestion
To use the JavaScript client library for Web3.Storage, you must first [obtain an API key](../how-tos/regenerate-api-key.md).
```

2021-07-15 13:32 UTC, johnnymatthews commented on docs/reference/client-library.md
> +The client library will automatically pack your uploads into a content addressible archive (CAR) file for uploading to the web3.storage service, which stores data as blocks prefixed with the content
```suggestion
The client library will automatically pack your uploads into a content addressible archive (CAR) file for uploading to the Web3.Storage service, which stores data as blocks prefixed with the content ID (CID) derived from the hash of the data. You can then use the CID to retrieve the file.
```

2021-07-15 13:32 UTC, johnnymatthews commented on docs/reference/client-library.md
> +The method returns a `Web3Response` object, which extends the [Fetch API response object](https://developer.mozilla.org/en-US/docs/Web/API/Response) to add two iterator methods unique to the web3.sto
```suggestion
The method returns a `Web3Response` object, which extends the [Fetch API response object](https://developer.mozilla.org/en-US/docs/Web/API/Response) to add two iterator methods unique to the Web3.Storage client library: `files()` and `unixFsIterator()`.
```

2021-07-15 13:32 UTC, johnnymatthews commented on docs/reference/client-library.md
> +> **Note**: In addition to the `files()` method, you can also use the `unixFsIterator()` method, which will return your requested files as a  `AsyncIterable<UnixFSEntry>` object, which is an iterable
```suggestion
:::tip Using UnixFSEntry
In addition to the `files()` method, you can also use the `unixFsIterator()` method, which will return your requested files as a  `AsyncIterable<UnixFSEntry>` object, which is an iterable collection of [`UnixFSEntry`](https://github.com/ipfs/js-ipfs-unixfs/blob/master/packages/ipfs-unixfs-exporter/README.md#unixfsentry) objects. Each object represents a file that was uploaded in the CAR file with the supplied CID. However, in the vast majority of cases, you will want to use the `files()` method. The exception is when you are retrieving files in a Node.js context, and you have existing IPFS tooling that knows how to consume `UnixFSEntry` objects.
:::
```

2021-07-15 16:39 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

### `docs/reference/client-library.md`:
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain an AP...
                                             ^^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```

2021-07-15 16:39 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

### `docs/reference/client-library.md`:
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain an AP...
                                             ^^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```

2021-07-15 16:39 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

### `docs/reference/client-library.md`:
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain an AP...
                                             ^^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```

2021-07-15 16:39 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

### `docs/reference/client-library.md`:
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain an AP...
                                             ^^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```

2021-07-15 16:39 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

### `docs/reference/client-library.md`:
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain an AP...
                                             ^^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```

2021-07-15 17:23 UTC, olizilla commented
Of note, i think we settled on calling it `Web3 Storage` in prose and `web3.storage` when referring to the url or the client library. Never caps&dots together `Web3.Storage`

2021-07-15 19:52 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

### `docs/how-tos/retrieve.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu/not-distributed.jpg
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...t Identifier (CID)  (opens new window). First you'll need to create a Web3.S...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... you have a client, you can call client.get, passing in a CID string:  The g...
                                             ^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...access to the retrieved IPFS data.  The files method returns an array of Web...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ...is guide, we'll use the gateway at dweb.link, but you can check the list of ...
                                             ^^^^
  ```



### `docs/reference/client-library.md`:
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain an AP...
                                             ^^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...iles being uploaded. See below for more details An {options} object is a JSO...
                                             ^^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```

2021-07-15 20:56 UTC, terichadbourne commented
@olizilla I thought we settled on Web3.Storage to match how NFT.Storage is being referred to elsewhere. Lemme know if you have a more recent verdict than the one at https://protocollabs.slack.com/archives/C01MPC37Z37/p1625154646106100?thread_ts=1625154546.104600&cid=C01MPC37Z37

2021-07-15 21:01 UTC, terichadbourne commented
Just confirmed with @jnthnvctr that this is still meant to be Web3.Storage (w/ dot, w/o space).

2021-07-15 21:12 UTC, terichadbourne commented
Note that the Tutorial section in the left nav was intentionally removed elsewhere because it's not a strict M1 goal to get that done, but it appears in this preview. I tried removing it by deleting the `docs/tutorials` folder but that only got rid of the contents and not the Tutorials header in left nav. @johndmulhausen Mind reminding me where else I need to go to remove it?

2021-07-15 21:14 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

### `docs/how-tos/retrieve.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu/not-distributed.jpg
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...t Identifier (CID)  (opens new window). First you'll need to create a Web3.S...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... you have a client, you can call client.get, passing in a CID string:  The g...
                                             ^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...access to the retrieved IPFS data.  The files method returns an array of Web...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ...is guide, we'll use the gateway at dweb.link, but you can check the list of ...
                                             ^^^^
  ```



### `docs/reference/client-library.md`:
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain an AP...
                                             ^^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...iles being uploaded. See below for more details An {options} object is a JSO...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```

2021-07-15 21:15 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

### `docs/how-tos/retrieve.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu/not-distributed.jpg
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...t Identifier (CID)  (opens new window). First you'll need to create a Web3.S...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... you have a client, you can call client.get, passing in a CID string:  The g...
                                             ^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...access to the retrieved IPFS data.  The files method returns an array of Web...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ...is guide, we'll use the gateway at dweb.link, but you can check the list of ...
                                             ^^^^
  ```



### `docs/reference/client-library.md`:
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain an AP...
                                             ^^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...iles being uploaded. See below for more details An {options} object is a JSO...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```

2021-07-16 04:40 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

### `docs/how-tos/retrieve.md`:
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... you have a client, you can call client.get, passing in a CID string:  The g...
                                             ^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...access to the retrieved IPFS data.  The files method returns an array of Web...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ...is guide, we'll use the gateway at dweb.link, but you can check the list of ...
                                             ^^^^
  ```



### `docs/reference/client-library.md`:
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain an AP...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```

2021-07-16 04:41 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

### `docs/how-tos/retrieve.md`:
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... you have a client, you can call client.get, passing in a CID string:  The g...
                                             ^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...access to the retrieved IPFS data.  The files method returns an array of Web...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ...is guide, we'll use the gateway at dweb.link, but you can check the list of ...
                                             ^^^^
  ```



### `docs/reference/client-library.md`:
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain an AP...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```

2021-07-16 18:22 UTC, yusefnapora approved these changes
This is great, thanks @johndmulhausen 👍 

I went ahead and pushed a few commits to fix up links and things, but I got a bit carried away and snuck in some edits to the storage howto (removing the references to web3-file). Hope you don't mind me cluttering up your PR :)

2021-07-16 18:22 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

### `docs/how-tos/retrieve.md`:
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... you have a client, you can call client.get, passing in a CID string:  The g...
                                             ^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...access to the retrieved IPFS data.  The files method returns an array of Web...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ...is guide, we'll use the gateway at dweb.link, but you can check the list of ...
                                             ^^^^
  ```
### `docs/how-tos/store.md`:
- The following link failed to connect:
  https://web3.storage/tokens/
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...APIs like fetch  (opens new window) and File  (opens new window). This guide...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ile objects manually: Unique file names Try to give each file a unique file ...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “file’s” (curly possessive apostrophe) or “file's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...one content archive, and linking to the files inside is much simpler if each...
                                             ^^^^^
  ```
- Consider using a more formal alternative to avoid the overused word “more”.<!--CategoryID:STYLE, RuleID: MORE_INFO-->
  ```
  ...the IPFS command line. You can also get more information about the status of...
                                             ^^^^^^^^^^^^^^^^
  ```


### `docs/reference/client-library.md`:
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain an AP...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```

2021-07-16 19:07 UTC, merged