Chore/change profile to account
web3-storage/docs pull request #102
Opened 2021-07-28 16:23 UTC by johnnymatthews

The _Profile_ page is now called _Account_. This PR updates all occurrences of `Profile` and `profile` to `Account` and `account`

2021-07-28 16:24 UTC, johnnymatthews commented on docs/how-tos/store.md
> -[site-profile]: https://web3.storage/profile/
This link is not used within this page.

2021-07-28 16:26 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2021-07-28 16:28 UTC, terichadbourne commented
@johnnymatthews I think you missed a page. Can you please search the full repo to ensure you've also caught the new generate an API token section

2021-07-28 16:29 UTC, johnnymatthews commented
Yeahp, my grep skills clearly aren't great.

2021-07-28 16:33 UTC, johnnymatthews commented
That should do it!

2021-07-28 16:34 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

### `docs/how-tos/generate-api-token.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://web3.storage/account
- The following link returned HTTP status code 302 (Found):
  https://web3.storage/tokens
- Consider a shorter alternative to avoid wordiness.<!--CategoryID:REDUNDANCY, RuleID: IN_ORDER_TO_PREMIUM-->
  ```
  ...You'll need a free Web3.Storage account in order to generate an API token. I...
                                             ^^^^^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...o see an invitation to do this from the Getting started section of your acco...
                                             ^^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...ill be easy for you to remember later.  TIP You don't have to use the same A...
                                             ^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ... to your clipboard. Keep your API token private Do not share your API token ...
                                             ^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... clipboard. Keep your API token private Do not share your API token with any...
                                             ^^
  ```
- It seems that “to” is missing before the verb.<!--CategoryID:GRAMMAR, RuleID: MISSING_TO_BETWEEN_BE_AND_VB-->
  ```
  ...emove it. Deleting a token is permanent Remember that if you delete an API t...
                                             ^^^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...nd line. If you haven't yet explored in depth how to store data using Web3.S...
                                             ^^^^^
  ```
- The verb “check out” can sound colloquial in this context. Consider using a more formal alternative.<!--CategoryID:STYLE, RuleID: CHECK_OUT_OUR-->
  ```
  ...h how to store data using Web3.Storage, check out the storage how-to guide f...
                                             ^^^^^^^^^
  ```
- Consider using a more formal alternative to avoid the overused word “more”.<!--CategoryID:STYLE, RuleID: MORE_INFO-->
  ```
  ...se the JavaScript client library to get more information about the status of...
                                             ^^^^^^^^^^^^^^^^
  ```

2021-07-28 16:42 UTC, jessicaschilling commented
@terichadbourne @johnnymatthews Please don't merge yet. We need to change screenshots as well. I'll take care of that.

2021-07-28 16:45 UTC, jessicaschilling commented
@terichadbourne @johnnymatthews Actually, strike that. It's better if I just do a separate PR replacing every screenshot. Feel free to merge.

2021-07-28 16:45 UTC, jessicaschilling approved these changes

2021-07-28 16:47 UTC, terichadbourne commented
@jessicaschilling We **can't merge this regardless** because the Account page doesn't exist yet - just qeueing it up. If the screenshots you're referring to are for the Profile/Account page you can put them here to trigger at the same time. You could hack the change for the screenshots in an inspector or wait until the change is actually made, whichever you prefer. 

@rafaelramalho19 can you please let us know once Profile has changed to Account on main site so we don't pull the trigger prematurely?

2021-07-28 16:49 UTC, terichadbourne requested changes
Just working the system to try to prevent us from accidentally merging before the Account page exists.

2021-07-28 16:49 UTC, jessicaschilling commented
@terichadbourne I'll repurpose https://github.com/web3-storage/docs/issues/86 to an "update all the screenshots" issue and psd-bash accordingly.

2021-07-28 19:23 UTC, filecorgi commented
- I optimized some images for you! See the commit with the comment `Automatically optimized images [ci skip].` in this PR for details.
- Vuepress build was successful!

### `docs/how-tos/generate-api-token.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://web3.storage/account
- The following link returned HTTP status code 302 (Found):
  https://web3.storage/tokens
- Consider a shorter alternative to avoid wordiness.<!--CategoryID:REDUNDANCY, RuleID: IN_ORDER_TO_PREMIUM-->
  ```
  ...You'll need a free Web3.Storage account in order to generate an API token. I...
                                             ^^^^^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...o see an invitation to do this from the Getting started section of your acco...
                                             ^^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...ill be easy for you to remember later.  TIP You don't have to use the same A...
                                             ^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ... to your clipboard. Keep your API token private Do not share your API token ...
                                             ^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... clipboard. Keep your API token private Do not share your API token with any...
                                             ^^
  ```
- It seems that “to” is missing before the verb.<!--CategoryID:GRAMMAR, RuleID: MISSING_TO_BETWEEN_BE_AND_VB-->
  ```
  ...emove it. Deleting a token is permanent Remember that if you delete an API t...
                                             ^^^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...nd line. If you haven't yet explored in depth how to store data using Web3.S...
                                             ^^^^^
  ```
- The verb “check out” can sound colloquial in this context. Consider using a more formal alternative.<!--CategoryID:STYLE, RuleID: CHECK_OUT_OUR-->
  ```
  ...h how to store data using Web3.Storage, check out the storage how-to guide f...
                                             ^^^^^^^^^
  ```
- Consider using a more formal alternative to avoid the overused word “more”.<!--CategoryID:STYLE, RuleID: MORE_INFO-->
  ```
  ...se the JavaScript client library to get more information about the status of...
                                             ^^^^^^^^^^^^^^^^
  ```

2021-07-29 12:31 UTC, alanshaw commented
> Just working the system to try to prevent us from accidentally merging before the Account page exists.

It exists now!

2021-07-29 13:24 UTC, merged

2021-07-29 13:24 UTC, jessicaschilling commented
@terichadbourne per https://github.com/web3-storage/docs/pull/102#issuecomment-889078060 , merging 😊