content: add list how-to guide
web3-storage/docs pull request #120
Opened 2021-07-30 16:58 UTC by yusefnapora

This add a how-to guide for listing your uploads using the JS client, with a mention that you can just view things on the files page as well.

closes #112

2021-07-30 17:00 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-tos/list.md`:
- The following link returned HTTP status code 302 (Found):
  https://web3.storage/files
- Did you mean “them”?<!--CategoryID:TYPOS, RuleID: CONFUSION_OF_THE_THEM_FOR-->
  ```
  ...opens new window) that can be used with the for await syntax  (opens new win...
                                             ^^^
  ```
- Possible agreement error.<!--CategoryID:GRAMMAR, RuleID: AGREEMENT_SENT_START-->
  ```
  ...an the total size of the files on disk. pins contains an array of objects de...
                                             ^^^^^^^^^^^^^
  ```
- Possible agreement error.<!--CategoryID:GRAMMAR, RuleID: AGREEMENT_SENT_START-->
  ```
  ... fast retrieval using the IPFS network. deals contains an array of objects d...
                                             ^^^^^^^^^^^^^^
  ```
- Two determiners in a row. Choose either “the” or “the”.<!--CategoryID:GRAMMAR, RuleID: DT_DT-->
  ```
  ... you can query an upload's status using the the cid.  By default the list me...
                                             ^^^^^^^
  ```
- Did you mean: “By default,”?<!--CategoryID:PUNCTUATION, RuleID: BY_DEFAULT_COMMA-->
  ```
  ... an upload's status using the the cid.  By default the list method returns i...
                                             ^^^^^^^^^^
  ```

2021-07-30 17:53 UTC, jessicaschilling requested changes
Thank you! Made some suggestions for consistency with other guides, and more clarity on web vs code approaches.

One other thing: Can you please add links where appropriate (noted in comments) to the list method when it exists in the JS client library page? Thank you!

2021-07-30 17:53 UTC, jessicaschilling commented on docs/how-tos/list.md
> +description: Learn how to list the files you've uploaded to Web3.Storage
```suggestion
description: Learn how to list the files you've uploaded to Web3.Storage in this quick how-to guide.
```
(for consistency with other how-tos)

2021-07-30 17:53 UTC, jessicaschilling commented on docs/how-tos/list.md
> +
```suggestion
In this how-to guide, you'll learn about the different ways that you can **list the files that you've uploaded to Web3.Storage.**
```

(for consistency with other how-tos)

2021-07-30 17:53 UTC, jessicaschilling commented on docs/how-tos/list.md
> +Once you've [stored some files][howto-store] using Web3.Storage, you can see a list of everything you've uploaded on the [Files page on the Web3.Storage website][site-files].
```suggestion
Once you've [stored some files][howto-store] using Web3.Storage, you'll want to see a list of what you've uplodaded. There are two ways you can do this:
- Using the 

## Using the Web3.Storage website

You can see a list of everything you've uploaded to Web3.Storage on the [Files page][site-files] on the Web3.Storage website. If you don't need to work with this list programmatically, using the website may be a simpler choice.
```
Adding some introductory comment to emphasize:
- there are two ways you can list files
- the programmatic one is preferable unless you're just looking for something simple

2021-07-30 17:53 UTC, jessicaschilling commented on docs/how-tos/list.md
> +The [Files page][site-files] provides a convenient overview of your stored data, with links to view your files using an [IPFS gateway][ipfs-docs-gateway] and information about how the data is being s
```suggestion
This [Files page][site-files] provides a convenient overview of your stored data, including links to view your files in your browser via an [IPFS gateway][ipfs-docs-gateway] and information about how the data is being stored on the [decentralized storage networks][concepts-decentralized-storage] that Web3.Storage uses under the hood.
```

2021-07-30 17:53 UTC, jessicaschilling commented on docs/how-tos/list.md
> +
```suggestion
## Using the Web3.Storage client
```

2021-07-30 17:53 UTC, jessicaschilling commented on docs/how-tos/list.md
> +You can also access a listing of your uploads from your application code using the Web3.Storage client. This guide will show you how to use the [JavaScript client library][reference-js-client] to fet
```suggestion
To easily integrate Web3.Storage programmatically in your apps or services, you can also access a listing of your uploads from your code using the Web3.Storage client. In the example below, this guide walks through how to use the [JavaScript client library][reference-js-client] to fetch a complete listing of all the data you've uploaded using Web3.Storage.
```

2021-07-30 17:53 UTC, jessicaschilling commented on docs/how-tos/list.md
> +## Installing the client
```suggestion
### Installing the client
```

2021-07-30 17:53 UTC, jessicaschilling commented on docs/how-tos/list.md
> +## Creating a client instance
```suggestion
### Creating a client instance
```

2021-07-30 17:53 UTC, jessicaschilling commented on docs/how-tos/list.md
> +## Listing your uploads
```suggestion
### Listing your uploads
```

2021-07-30 17:53 UTC, jessicaschilling commented on docs/how-tos/list.md
> +### Listing a subset of uploads
```suggestion
#### Listing a subset of uploads
```

2021-07-30 17:53 UTC, jessicaschilling commented on docs/how-tos/list.md
> +
```suggestion
[reference-js-constructor]: ../reference/client-library.md#constructor
```
to fix a broken link above

2021-07-30 17:53 UTC, jessicaschilling commented on docs/how-tos/list.md
> +You can use any access token associated with your account, not just the one you used to upload your files! See the [Generate API token page][howto-gen-token] for more about token management.
```suggestion
You can use any API token associated with your account, not just the one you originally used to upload your files! See the [Generate API token page][howto-gen-token] for more about token management.
```

2021-07-30 17:53 UTC, jessicaschilling commented on docs/how-tos/list.md
> +The `Web3Storage` client object's `list` method returns an [async iterable][js-async-iterable-explainer] that can be used with the [`for await` syntax][mdn-for-await-of] to read information about eac
Can you please add a link for ``'list' method` once it gets added to the client library page?

2021-07-30 17:53 UTC, jessicaschilling commented on docs/how-tos/list.md
> +::: tip "Want more details about storage?"
```suggestion
::: tip Want more details about storage?
```
No quotes necessary 😊

2021-07-30 17:53 UTC, jessicaschilling commented on docs/how-tos/list.md
> +By default the `list` method returns information about all uploads made using your Web3.Storage account. You can optionally restrict the listing to contain entries that were uploaded before a given t
Can you please add a link for ``'list' method` once it gets added to the client library page?

2021-07-30 17:53 UTC, jessicaschilling commented on docs/how-tos/list.md
> +By default the `list` method returns information about all uploads made using your Web3.Storage account. You can optionally restrict the listing to contain entries that were uploaded before a given t
```suggestion
By default. the `list` method returns information about all uploads made using your Web3.Storage account. You can optionally restrict the listing in two ways:
-  Only contain entries that were uploaded before a given timestamp.
- Limit the total number of returned entries.
```

2021-07-30 17:53 UTC, jessicaschilling commented on docs/how-tos/list.md
> +Here's an example of fetching the first ten uploads made on the previous day:
```suggestion
Here's an example of fetching the first 10 uploads made on the previous day:
```

2021-07-30 19:13 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-tos/list.md`:
- The following link returned HTTP status code 302 (Found):
  https://web3.storage/files
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ...nce you've stored some files using Web3.Storage, you'll want to see a list o...
                                             ^^^^^^^
  ```
- Possible typo. Did you mean “the” or “You”?<!--CategoryID:GRAMMAR, RuleID: DT_PRP-->
  ```
  ...ere are two ways you can do this: Using the  You can see a list of everythin...
                                             ^^^^^^^^
  ```
- Did you mean “these”?<!--CategoryID:GRAMMAR, RuleID: THIS_NNS_VB-->
  ```
  ...g the website may be a simpler choice.  This Files page  (opens new window) ...
                                             ^^^^
  ```
- Did you mean “them”?<!--CategoryID:TYPOS, RuleID: CONFUSION_OF_THE_THEM_FOR-->
  ```
  ...opens new window) that can be used with the for await syntax  (opens new win...
                                             ^^^
  ```
- Possible agreement error.<!--CategoryID:GRAMMAR, RuleID: AGREEMENT_SENT_START-->
  ```
  ...an the total size of the files on disk. pins contains an array of objects de...
                                             ^^^^^^^^^^^^^
  ```
- Possible agreement error.<!--CategoryID:GRAMMAR, RuleID: AGREEMENT_SENT_START-->
  ```
  ... fast retrieval using the IPFS network. deals contains an array of objects d...
                                             ^^^^^^^^^^^^^^
  ```
- Two determiners in a row. Choose either “the” or “the”.<!--CategoryID:GRAMMAR, RuleID: DT_DT-->
  ```
  ... you can query an upload's status using the the cid.  By default. the list m...
                                             ^^^^^^^
  ```
- Did you mean: “By default,”?<!--CategoryID:PUNCTUATION, RuleID: BY_DEFAULT_COMMA-->
  ```
  ... an upload's status using the the cid.  By default. the list method returns ...
                                             ^^^^^^^^^^
  ```

2021-08-02 15:41 UTC, terichadbourne commented
Changing our requested Spark reviewer from Vasco to @alanshaw due to vacation schedules. 🙏

2021-08-02 15:52 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-tos/list.md`:
- The following link returned HTTP status code 302 (Found):
  https://web3.storage/files
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ...nce you've stored some files using Web3.Storage, you'll want to see a list o...
                                             ^^^^^^^
  ```
- Possible typo. Did you mean “the” or “You”?<!--CategoryID:GRAMMAR, RuleID: DT_PRP-->
  ```
  ...ere are two ways you can do this: Using the  You can see a list of everythin...
                                             ^^^^^^^^
  ```
- Did you mean “these”?<!--CategoryID:GRAMMAR, RuleID: THIS_NNS_VB-->
  ```
  ...g the website may be a simpler choice.  This Files page  (opens new window) ...
                                             ^^^^
  ```
- Did you mean “them”?<!--CategoryID:TYPOS, RuleID: CONFUSION_OF_THE_THEM_FOR-->
  ```
  ...opens new window) that can be used with the for await syntax  (opens new win...
                                             ^^^
  ```
- Possible agreement error.<!--CategoryID:GRAMMAR, RuleID: AGREEMENT_SENT_START-->
  ```
  ...an the total size of the files on disk. pins contains an array of objects de...
                                             ^^^^^^^^^^^^^
  ```
- Possible agreement error.<!--CategoryID:GRAMMAR, RuleID: AGREEMENT_SENT_START-->
  ```
  ... fast retrieval using the IPFS network. deals contains an array of objects d...
                                             ^^^^^^^^^^^^^^
  ```
- Two determiners in a row. Choose either “the” or “the”.<!--CategoryID:GRAMMAR, RuleID: DT_DT-->
  ```
  ... you can query an upload's status using the the cid.  By default, the list m...
                                             ^^^^^^^
  ```

2021-08-02 15:55 UTC, yusefnapora commented
Last commit adds links to the reference section from #121, so it's probably best to merge that one first.

2021-08-02 18:26 UTC, johndmulhausen commented on docs/how-tos/list.md
> +<!-- TODO: replace with example that includes deal status -->
You can grab the example from the client reference, I got one there:

```json
{
  "name": "cat pics",
  "cid": "bafkreifzjut3te2nhyekklss27nh3k72ysco7y32koao5eei66wof36n5e",
  "created": "2021-07-14T19:27:14.934572Z",
  "dagSize": 101,
  "pins": [{
    "peerId": "12D3KooWR1Js",
    "peerName": "peerName",
    "region": "peerRegion",
    "status": "Pinned"
  }],
  "deals": [{
    "dealId": 12345,
    "miner": "f99",
    "status": "Active",
    "pieceCid": "bafkreifzjut3te2nhyekklss27nh3k72ysco7y32koao5eei66wof36n5e",
    "dataCid": "bafkreifzjut3te2nhyekklss27nh3k72ysco7y32koao5eei66wof36n5e",
    "dataModelSelector": "Links/0/Links",
    "activation": "2021-07-14T19:27:14.934572Z",
    "created": "2021-07-14T19:27:14.934572Z",
    "updated": "2021-07-14T19:27:14.934572Z"
  }]
}
```

2021-08-02 18:27 UTC, yusefnapora commented on docs/how-tos/list.md
> +<!-- TODO: replace with example that includes deal status -->
good call, thanks 👍

2021-08-02 18:29 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-tos/list.md`:
- The following link returned HTTP status code 302 (Found):
  https://web3.storage/files
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ...nce you've stored some files using Web3.Storage, you'll want to see a list o...
                                             ^^^^^^^
  ```
- Possible typo. Did you mean “the” or “You”?<!--CategoryID:GRAMMAR, RuleID: DT_PRP-->
  ```
  ...ere are two ways you can do this: Using the  You can see a list of everythin...
                                             ^^^^^^^^
  ```
- Did you mean “these”?<!--CategoryID:GRAMMAR, RuleID: THIS_NNS_VB-->
  ```
  ...g the website may be a simpler choice.  This Files page  (opens new window) ...
                                             ^^^^
  ```
- Did you mean “them”?<!--CategoryID:TYPOS, RuleID: CONFUSION_OF_THE_THEM_FOR-->
  ```
  ...opens new window) that can be used with the for await syntax  (opens new win...
                                             ^^^
  ```
- Possible agreement error.<!--CategoryID:GRAMMAR, RuleID: AGREEMENT_SENT_START-->
  ```
  ...an the total size of the files on disk. pins contains an array of objects de...
                                             ^^^^^^^^^^^^^
  ```
- Possible agreement error.<!--CategoryID:GRAMMAR, RuleID: AGREEMENT_SENT_START-->
  ```
  ... fast retrieval using the IPFS network. deals contains an array of objects d...
                                             ^^^^^^^^^^^^^^
  ```
- Two determiners in a row. Choose either “the” or “the”.<!--CategoryID:GRAMMAR, RuleID: DT_DT-->
  ```
  ... you can query an upload's status using the the cid.  By default, the list m...
                                             ^^^^^^^
  ```

2021-08-02 18:30 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-tos/list.md`:
- The following link returned HTTP status code 302 (Found):
  https://web3.storage/files
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ...nce you've stored some files using Web3.Storage, you'll want to see a list o...
                                             ^^^^^^^
  ```
- Possible typo. Did you mean “the” or “You”?<!--CategoryID:GRAMMAR, RuleID: DT_PRP-->
  ```
  ...ere are two ways you can do this: Using the  You can see a list of everythin...
                                             ^^^^^^^^
  ```
- Did you mean “these”?<!--CategoryID:GRAMMAR, RuleID: THIS_NNS_VB-->
  ```
  ...g the website may be a simpler choice.  This Files page  (opens new window) ...
                                             ^^^^
  ```
- Did you mean “them”?<!--CategoryID:TYPOS, RuleID: CONFUSION_OF_THE_THEM_FOR-->
  ```
  ...opens new window) that can be used with the for await syntax  (opens new win...
                                             ^^^
  ```
- Possible agreement error.<!--CategoryID:GRAMMAR, RuleID: AGREEMENT_SENT_START-->
  ```
  ...an the total size of the files on disk. pins contains an array of objects de...
                                             ^^^^^^^^^^^^^
  ```
- Possible agreement error.<!--CategoryID:GRAMMAR, RuleID: AGREEMENT_SENT_START-->
  ```
  ... fast retrieval using the IPFS network. deals contains an array of objects d...
                                             ^^^^^^^^^^^^^^
  ```
- Two determiners in a row. Choose either “the” or “the”.<!--CategoryID:GRAMMAR, RuleID: DT_DT-->
  ```
  ... you can query an upload's status using the the cid.  By default, the list m...
                                             ^^^^^^^
  ```

2021-08-02 18:33 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-tos/list.md`:
- The following link returned HTTP status code 302 (Found):
  https://web3.storage/files
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ...nce you've stored some files using Web3.Storage, you'll want to see a list o...
                                             ^^^^^^^
  ```
- Possible typo. Did you mean “the” or “You”?<!--CategoryID:GRAMMAR, RuleID: DT_PRP-->
  ```
  ...ere are two ways you can do this: Using the  You can see a list of everythin...
                                             ^^^^^^^^
  ```
- Did you mean “these”?<!--CategoryID:GRAMMAR, RuleID: THIS_NNS_VB-->
  ```
  ...g the website may be a simpler choice.  This Files page  (opens new window) ...
                                             ^^^^
  ```
- Did you mean “them”?<!--CategoryID:TYPOS, RuleID: CONFUSION_OF_THE_THEM_FOR-->
  ```
  ...opens new window) that can be used with the for await syntax  (opens new win...
                                             ^^^
  ```
- Possible agreement error.<!--CategoryID:GRAMMAR, RuleID: AGREEMENT_SENT_START-->
  ```
  ...an the total size of the files on disk. pins contains an array of objects de...
                                             ^^^^^^^^^^^^^
  ```
- Possible agreement error.<!--CategoryID:GRAMMAR, RuleID: AGREEMENT_SENT_START-->
  ```
  ... fast retrieval using the IPFS network. deals contains an array of objects d...
                                             ^^^^^^^^^^^^^^
  ```

2021-08-03 11:04 UTC, alanshaw requested changes

2021-08-03 11:06 UTC, alanshaw commented on code-snippets/how-to/example-listing-upload.json
> +    "updated": "2021-07-14T19:27:14.934572Z"
https://github.com/web3-storage/web3.storage/issues/284

2021-08-03 14:20 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-tos/list.md`:
- The following link returned HTTP status code 302 (Found):
  https://web3.storage/files
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ...nce you've stored some files using Web3.Storage, you'll want to see a list o...
                                             ^^^^^^^
  ```
- Possible typo. Did you mean “the” or “You”?<!--CategoryID:GRAMMAR, RuleID: DT_PRP-->
  ```
  ...ere are two ways you can do this: Using the  You can see a list of everythin...
                                             ^^^^^^^^
  ```
- Did you mean “these”?<!--CategoryID:GRAMMAR, RuleID: THIS_NNS_VB-->
  ```
  ...g the website may be a simpler choice.  This Files page  (opens new window) ...
                                             ^^^^
  ```
- Did you mean “them”?<!--CategoryID:TYPOS, RuleID: CONFUSION_OF_THE_THEM_FOR-->
  ```
  ...opens new window) that can be used with the for await syntax  (opens new win...
                                             ^^^
  ```
- Possible agreement error.<!--CategoryID:GRAMMAR, RuleID: AGREEMENT_SENT_START-->
  ```
  ...an the total size of the files on disk. pins contains an array of objects de...
                                             ^^^^^^^^^^^^^
  ```
- Possible agreement error.<!--CategoryID:GRAMMAR, RuleID: AGREEMENT_SENT_START-->
  ```
  ... fast retrieval using the IPFS network. deals contains an array of objects d...
                                             ^^^^^^^^^^^^^^
  ```

2021-08-03 19:54 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-tos/list.md`:
- The following link returned HTTP status code 302 (Found):
  https://web3.storage/files
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ...nce you've stored some files using Web3.Storage, you'll want to see a list o...
                                             ^^^^^^^
  ```
- Did you mean “these”?<!--CategoryID:GRAMMAR, RuleID: THIS_NNS_VB-->
  ```
  ...g the website may be a simpler choice.  This Files page  (opens new window) ...
                                             ^^^^
  ```
- Did you mean “them”?<!--CategoryID:TYPOS, RuleID: CONFUSION_OF_THE_THEM_FOR-->
  ```
  ...opens new window) that can be used with the for await syntax  (opens new win...
                                             ^^^
  ```
- Possible agreement error.<!--CategoryID:GRAMMAR, RuleID: AGREEMENT_SENT_START-->
  ```
  ...an the total size of the files on disk. pins contains an array of objects de...
                                             ^^^^^^^^^^^^^
  ```
- Possible agreement error.<!--CategoryID:GRAMMAR, RuleID: AGREEMENT_SENT_START-->
  ```
  ... fast retrieval using the IPFS network. deals contains an array of objects d...
                                             ^^^^^^^^^^^^^^
  ```

2021-08-03 20:11 UTC, merged