Add "list()" to JS Client Ref
web3-storage/docs pull request #121
Opened 2021-07-30 22:02 UTC by johndmulhausen

^ As mentioned in the title

2021-07-30 22:04 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘your’ (possessive pronoun) seems less likely than ‘you’ (personal pronoun).<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_YOUR_YOU-->
  ```
  ...ties that can be used as parameters for your put() operation: name String. T...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...rameters for your put() operation: name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...ens new window) format. pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...l to put(). See the Response tab in the Examples section for an illustration...
                                             ^^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-07-30 22:10 UTC, jessicaschilling requested changes
Can you please:
- swap the order of `Parameters` and `Return value` for consistency with other methods
- take both of those out of the tab box, since they're not specific to the contents of the tabs

Thank you!

![image](https://user-images.githubusercontent.com/1507828/127716289-dbafcc85-161a-49ef-aa90-2e5074930b2f.png)

2021-07-31 07:42 UTC, johndmulhausen commented
> Can you please:
> 
> * swap the order of `Parameters` and `Return value` for consistency with other methods
> * take both of those out of the tab box, since they're not specific to the contents of the tabs
> 
> Thank you!

Done!

2021-07-31 07:44 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘your’ (possessive pronoun) seems less likely than ‘you’ (personal pronoun).<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_YOUR_YOU-->
  ```
  ...ties that can be used as parameters for your put() operation: name String. T...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...rameters for your put() operation: name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...ens new window) format. pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...l to put(). See the Response tab in the Examples section for an illustration.
                                             ^^^^^^^^
  ```

2021-07-31 13:06 UTC, alanshaw commented on docs/reference/client-library.md
> +The return value for `list()` is the same as the return value for `status()` but with one extra propery: a string field called `name` that corresponds to the value given passed to the `name` paramete
This is not quite correct, the return value is an Async Iterable, and values yielded from it are the same as the return value for `status()`, with an extra `name` property.

I don't know if important, but the `created` date on these objects will be the date the user uploaded the file(s) but in the status API it's the date the CID was first seen. i.e. someone may have uploaded that same file before you.

2021-08-02 15:17 UTC, yusefnapora commented on docs/reference/client-library.md
> +The return value for `list()` is the same as the return value for `status()` but with one extra propery: a string field called `name` that corresponds to the value given passed to the `name` paramete
Good catch about the return value. We should call out that it's an async iterable - the way it's worded now suggests you'll get a plain object response.

2021-08-02 15:20 UTC, yusefnapora requested changes
Apart from Alan's comment about the return value, this looks good to me. Feel free to merge once that's in 👍

2021-08-02 16:34 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...d the same file(s). ::: pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-02 16:37 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-02 16:38 UTC, yusefnapora approved these changes
nice!

2021-08-02 16:39 UTC, johndmulhausen commented
Thanks for the reviews, @alanshaw , @jessicaschilling , @yusefnapora and @filecorgi !

2021-08-02 16:39 UTC, merged