Adds min reqs.
web3-storage/docs pull request #144
Opened 2021-08-05 15:27 UTC by johnnymatthews

Closes #127

2021-08-05 15:29 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

### `docs/community/help-and-support.md`:
- The following link returned HTTP status code 302 (Found):
  https://filecoin.io/slack
- The following link returned HTTP status code 302 (Found):
  https://github.com/web3-storage/web3.storage/issues/new/choose
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... channel on Slack.  (opens new window)  Found a bug, or have a feature reque...
                                             ^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...eb3.Storage service  (opens new window) File an issue for the Web3.Storage d...
                                             ^^^^
  ```
- Consider using “email”.<!--CategoryID:REDUNDANCY, RuleID: SEND_AN_EMAIL-->
  ```
  ...  Need more space on Web3.Storage? Just send an email to request more. The W...
                                             ^^^^^^^^^^^^^^^^
  ```

### `docs/how-tos/retrieve.md`:
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ...is guide, we'll use the gateway at dweb.link, but you can see more worldwide...
                                             ^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ...uy7pcu, you can make a URL for the dweb.link gateway as follows: bafybeidd2g...
                                             ^^^^
  ```
- Use ‘own’ only if you want to emphasize that something belongs to a person or thing or was done by a person or thing. Consider writing “your”.<!--CategoryID:REDUNDANCY, RuleID: PRP_OWN-->
  ```
  ... so if you're looking to link to one of your own files, you don't even have ...
                                             ^^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... you have a client, you can call client.get, passing in a CID string:  The g...
                                             ^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...S data: files and unixFsIterator(). The files method returns an array of Web...
                                             ^^^^^
  ```
- In American English, the usual prepositions after ‘different’ are “from” or “than”.<!--CategoryID:AMERICAN_ENGLISH_COLLOCATIONS, RuleID: DIFFERENT_TO-->
  ```
  ...save the file to. This can be different to <FILE NAME>. Desktop/output-file....
                                             ^^
  ```
- In American English, the usual prepositions after ‘different’ are “from” or “than”.<!--CategoryID:AMERICAN_ENGLISH_COLLOCATIONS, RuleID: DIFFERENT_TO-->
  ```
  ...save the file to. This can be different to <FILE NAME>. Desktop/output-file....
                                             ^^
  ```
- In American English, the usual prepositions after ‘different’ are “from” or “than”.<!--CategoryID:AMERICAN_ENGLISH_COLLOCATIONS, RuleID: DIFFERENT_TO-->
  ```
  ...save the file to. This can be different to <FILE NAME>. Desktop/output-file....
                                             ^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...ent to <FILE NAME>. Desktop/output-file.txt Your complete command should loo...
                                             ^^^
  ```
- The verb “check out” can sound colloquial in this context. Consider using a more formal alternative.<!--CategoryID:STYLE, RuleID: CHECK_OUT_OUR-->
  ```
  ...h how to store data using Web3.Storage, check out the storage how-to guide f...
                                             ^^^^^^^^^
  ```
- Consider using a more formal alternative to avoid the overused word “more”.<!--CategoryID:STYLE, RuleID: MORE_INFO-->
  ```
  ... can also use the client library to get more information about the status of...
                                             ^^^^^^^^^^^^^^^^
  ```
### `docs/how-tos/store.md`:
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...s such as fetch  (opens new window) and File  (opens new window). This guide...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ....storage package to your dependencies:  First we need to create a Web3.Stora...
                                             ^^^^^
  ```
- The phrase ‘a lot of’ might be wordy. Consider using “many”.<!--CategoryID:REDUNDANCY, RuleID: A_LOT_OF-->
  ```
  ...ent method: If you expect to be loading a lot of large files, you may be bet...
                                             ^^^^^^^^
  ```
- Apostrophe might be missing. Did you mean “file’s” (curly possessive apostrophe) or “file's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...one content archive, and linking to the files inside is much easier if each ...
                                             ^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...an array of Files, uploading is simple: IMPORTANT Deleting files from the We...
                                             ^^^^^^^^^
  ```
- Possibly missing article found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_THE-->
  ```
  ... IMPORTANT Deleting files from the Web3.Storage site's Files page  (opens ne...
                                             ^^^^^^^
  ```
- Consider using a more formal alternative to avoid the overused word “more”.<!--CategoryID:STYLE, RuleID: MORE_INFO-->
  ```
  ...to guide on retrieval. You can also get more information about the status of...
                                             ^^^^^^^^^^^^^^^^
  ```
### `docs/reference/client-library.md`:
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘your’ (belonging to you) seems less likely than ‘you’ (personal pronoun).<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_YOUR_YOU-->
  ```
  ...ties that can be used as parameters for your put() operation: name String. T...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...rameters for your put() operation: name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-- [...]

2021-08-05 15:30 UTC, jessicaschilling requested changes
Minor consistency fix, otherwise LGTM!

2021-08-05 15:30 UTC, jessicaschilling commented on docs/reference/client-library.md
> +- [Nodejs](https://nodejs.org/en/) `14.0.0`
```suggestion
- [Node.js](https://nodejs.org/en/) `14.0.0`
```

2021-08-05 15:39 UTC, johnnymatthews commented on docs/reference/client-library.md
> +- [Nodejs](https://nodejs.org/en/) `14.0.0`
Still waiting on the day that someone decides to make `.js` a TLD...

2021-08-05 15:40 UTC, jessicaschilling commented on docs/reference/client-library.md
> +- [Nodejs](https://nodejs.org/en/) `14.0.0`
I have The Fear.

2021-08-05 17:53 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-05 17:54 UTC, yusefnapora commented
@johnnymatthews I noticed a little conflict with main after I merged in #133, so I pushed up a merge commit. Just FYI :)

2021-08-16 16:18 UTC, jessicaschilling approved these changes

2021-08-16 16:18 UTC, atopal reviewed
LGTM!

2021-08-16 16:19 UTC, merged