HTTP API Reference Docs: Option 2 - ReDoc
web3-storage/docs pull request #152
Opened 2021-08-05 21:32 UTC by johndmulhausen

I had thought that ReDoc could potentially render inside the content column in our theme but in fact that was very awkward. The best treatment I could put together was as a flat HTML file using scraped Vuepress build output for JS/CSS and then grabbing the navbar HTML to stick at the top, overriding `position: sticky` to be `position: relative` so that it scrolls away.

2021-08-05 21:34 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build failed...

```

> web3-storage-docs@2.0.0 docs:build /home/runner/work/docs/docs
> vuepress build docs

wait Extracting site metadata...
tip Apply local theme at /home/runner/work/docs/docs/docs/.vuepress/theme...
tip Apply theme local (extends @vuepress/theme-default) ...
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/last-updated (i.e. "@vuepress/plugin-last-updated") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
tip Apply plugin vuepress-plugin-speedcurve ...
tip Apply plugin clean-urls (i.e. "vuepress-plugin-clean-urls") ...
tip Apply plugin seo (i.e. "vuepress-plugin-seo") ...
tip Apply plugin canonical (i.e. "vuepress-plugin-canonical") ...
tip Apply plugin sitemap (i.e. "vuepress-plugin-sitemap") ...
tip Apply plugin robots (i.e. "vuepress-plugin-robots") ...
tip Apply plugin @vuepress/html-redirect (i.e. "@vuepress/plugin-html-redirect") ...
tip Apply plugin chunkload-redirect (i.e. "vuepress-plugin-chunkload-redirect") ...
tip Apply plugin ipfs (i.e. "vuepress-plugin-ipfs") ...
tip Apply plugin tabs (i.e. "vuepress-plugin-tabs") ...
tip Apply plugin code-copy (i.e. "vuepress-plugin-code-copy") ...
[info] [webpackbar] Compiling Client
[info] [webpackbar] Compiling Server
[success] [webpackbar] Server: Compiled successfully in 12.32s
[success] [webpackbar] Client: Compiled successfully in 20.09s
wait Rendering static HTML...
[vuepress] No matching page found for sidebar item "/http-api.html"
[vuepress] No matching page found for sidebar item "/http-api.html"
[vuepress] No matching page found for sidebar item "/http-api.html"
[Vue warn]: Error in render: "TypeError: Cannot read property 'match' of undefined"

found in

---> <SidebarLinks>
       <DropdownTransition>
         <SidebarGroup>
           <SidebarLinks>
             <Sidebar>
               <Layout>
                 <Anonymous>
                   <Root>
[vuepress] No matching page found for sidebar item "/http-api.html"
[vuepress] No matching page found for sidebar item "/http-api.html"
[vuepress] No matching page found for sidebar item "/http-api.html"
[Vue warn]: Error in render: "TypeError: Cannot read property 'match' of undefined"

found in

---> <SidebarLinks>
       <DropdownTransition>
         <SidebarGroup>
           <SidebarLinks>
             <Sidebar>
               <Layout>
                 <Anonymous>
                   <Root>
[vuepress] No matching page found for sidebar item "/http-api.html"
[vuepress] No matching page found for sidebar item "/http-api.html"
[vuepress] No matching page found for sidebar item "/http-api.html"
[Vue warn]: Error in render: "TypeError: Cannot read property 'match' of undefined"

found in

---> <SidebarLinks>
       <DropdownTransition>
         <SidebarGroup>
           <SidebarLinks>
             <Sidebar>
               <Layout>
                 <Anonymous>
                   <Root>
[vuepress] No matching page found for sidebar item "/http-api.html"
[vuepress] No matching page found for sidebar item "/http-api.html"
[vuepress] No matching page found for sidebar item "/http-api.html"
[Vue warn]: Error in render: "TypeError: Cannot read property 'match' of undefined"

found in

---> <SidebarLinks>
       <DropdownTransition>
         <SidebarGroup>
           <SidebarLinks>
             <Sidebar>
               <Layout>
                 <Anonymous>
                   <Root>
[vuepress] No matching page found for sidebar item "/http-api.html"
[vuepress] No matching page found for sidebar item "/http-api.html"
[vuepress] No matching page found for sidebar item "/http-api.html"
[Vue warn]: Error in render: "TypeError: Cannot read property 'match' of undefined"

found in

---> <SidebarLinks>
       <DropdownTransition>
         <SidebarGroup>
           <SidebarLinks>
             <Sidebar>
               <Layout>
                 <Anonymous>
                   <Root>
[vuepress] No matching page found for sidebar item "/http-api.html"
[vuepress] No matching page found for sidebar item "/http-api.html"
[vuepress] No matching page found for sidebar item "/http-api.html"
[Vue warn]: Error in render: "TypeError: Cannot read property 'match' of undefined"

found in

---> <SidebarLinks>
       <DropdownTransition>
         <SidebarGroup>
           <SidebarLinks>
             <Sidebar>
               <Layout>
                 <Anonymous>
                   <Root>
[vuepress] No matching page found for sidebar item "/http-api.html"
[vuepress] No matching page found for sidebar item "/http-api.html"
[vuepress] No matching page found for sidebar item "/http-api.html"
[Vue warn]: Error in render: "TypeError: Cannot read property 'match' of undefined"

found in

---> <SidebarLinks>
       <DropdownTransition>
         <SidebarGroup>
           <SidebarLinks>
             <Sidebar>
               <Layout>
                 <Anonymous>
                   <Root>
[vuepress] No matching page found for sidebar item "/http-api.html"
[vuepress] No matching page found for sidebar item "/http-api.html"
[vuepress] No matching page found for sidebar item "/http-api.html"
[Vue warn]: Error in render: "TypeError: Cannot read property 'match' of undefined"

found in

---> <SidebarLinks>
       <DropdownTransition>
         <SidebarGroup>
           <SidebarLinks>
             <Sidebar>
               <Layout>
                 <Anonymous>
                   <Root>
[vuepress] No matching page found for sidebar item "/http-api.html"
[vuepress] No matching page found for sidebar item "/http-api.html"
[vuepress] No matching page found for sidebar item "/http-api.html"
[Vue warn]: Error in render: "TypeError: Cannot read property 'match' of undefined"

found in

---> <SidebarLinks>
       <DropdownTransition>
         <SidebarGroup>
           <SidebarLinks>
             <Sidebar>
               <Layout>
                 <Anonymous>
                   <Root>
[vuepress] No matching page found for sidebar item "/http-api.html"
[vuepress] No matching page found for sidebar item "/http-api.html"
[vuepress] No matching page found for sidebar item "/http-api.html"
[Vue warn]: Error in render: "TypeError: Cannot read property 'match' of undefined"

found in

---> <SidebarLinks>
       <DropdownTransition>
         <SidebarGroup>
           <SidebarLinks>
             <Sidebar>
               <Layout>
                 <Anonymous>
                   <Root>
[vuepress] No matching page found for sidebar item "/http-api.html"
[vuepress] No matching page found for sidebar item "/http-api.html"
[vuepress] No matching page found for sidebar item "/http-api.html"
[Vue warn]: Error in render: "TypeError: Cannot read property 'match' of undefined"

found in

---> <SidebarLinks>
       <DropdownTransition>
         <SidebarGroup>
           <SidebarLinks>
             <Sidebar>
               <Layout>
                 <Anonymous>
                   <Root>
error Error rendering /: false
undefined
error Error rendering /concepts/decentralized-storage/: false
undefined
error Error rendering /community/help-and-support/: false
undefined
error Error rendering /concepts/content-addressing/: false
undefined
error Error rendering /how-tos/generate-api-token/: false
undefined
error Error rendering /how-tos/list/: false
undefined
error Error rendering /how-tos/query/: false
undefined
error Error rendering /how-tos/retrieve/: false
undefined
error Error rendering /how-tos/store/: false
undefined
error Error rendering /reference/: false
undefined
error Error rendering /reference/client-library/: false
undefined
TypeError: Cannot read property 'match' of undefined
    at getHash (node_modules/@vuepress/theme-d [...]

2021-08-05 21:57 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
- No markdown files were changed, so no page checks were run!

2021-08-06 14:26 UTC, yusefnapora commented on docs/.vuepress/config.js
> +              ['http://localhost:8080/http-api.html','HTTP API Reference'],
This reference to localhost could be why the styles on the preview are messed up. I guess if you give it a file path, Vuepress tries to mess with it?

2021-08-06 14:29 UTC, yusefnapora commented on docs/.vuepress/config.js
> +              ['http://localhost:8080/http-api.html','HTTP API Reference'],
nevermind, I think this just affects the links in the side nav. the css is probably something else

2021-08-06 20:39 UTC, johndmulhausen commented on docs/.vuepress/config.js
> +              ['http://localhost:8080/http-api.html','HTTP API Reference'],
Yes; it just fails to render anything under reference if you set it to "/http-api.html" -- it backs off if you treat it like a full external link, which we probably want to do anyway given that it exits the main site experience.

2021-08-06 21:29 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
- No markdown files were changed, so no page checks were run!

2021-08-06 22:03 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
- No markdown files were changed, so no page checks were run!

2021-08-13 20:26 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-16 14:11 UTC, yusefnapora reviewed
This is looking nice :) Hopefully we can figure out the css thing - you're probably on to something with Vuepress mangling the filenames with a hash fingerprint.

Also weird that the fleek build seems to have been running for two days 😕 I guess we'll see if it's a one-off thing when we push a new commit...

2021-08-16 16:26 UTC, jessicaschilling commented
@yusefnapora I tried manually canceling the days-old deploy in Fleek's UI and that failed, unfortunately. Hopefully pushing a new commit will kick it into re-trying altogether.

Is this something I can copy edit in the meantime, or would it make more sense to wait?

2021-08-16 22:03 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-16 22:03 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-16 22:04 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 504 (Gateway Timeout):
  https://spec.filecoin.io/systems/filecoin_files/piece/
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-17 03:29 UTC, johndmulhausen commented
> @yusefnapora I tried manually canceling the days-old deploy in Fleek's UI and that failed, unfortunately. Hopefully pushing a new commit will kick it into re-trying altogether.
> 
> Is this something I can copy edit in the meantime, or would it make more sense to wait?

You can definitely copy edit, @jessicaschilling !

2021-08-17 16:46 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-17 18:50 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-17 19:03 UTC, jessicaschilling approved these changes
@johndmulhausen @yusefnapora - I did a round of copy editing in https://github.com/web3-storage/docs/pull/152/commits/e0288f4c333902393631b4e27ebc50a4ddc12437 . After that, all LGTM unless something substantially changes in the interim.

Also pushed https://github.com/web3-storage/docs/pull/152/commits/e0288f4c333902393631b4e27ebc50a4ddc12437 for some light-touch CSS to make it more visually similar to the rest of the site without making it too different from standard Redoc style.

Looks like the current Fleek preview actually brings in CSS just fine — I think it was just a build issue on Fleek's end when previews were wonky the other day.

2021-08-17 19:06 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 07:08 UTC, sliard commented on docs/.vuepress/public/schema.yml
> +      requestBody:
missing {cid} parameter description ?

openapitools have error without :
    attribute paths.'/car/{cid}'. Declared path parameter cid needs to be defined as a path parameter in path or operation level

2021-08-20 13:10 UTC, alanshaw requested changes
A lot of fixes here. It will need another review after all is fixed to verify everything is in order.

2021-08-20 13:10 UTC, alanshaw commented on docs/.vuepress/public/schema.yml
> +              enum: [Token is not valid, Session expired]
```suggestion
    ForbiddenErrorResponse:
      type: object
      properties:
        name:
          type: string
          default: HTTP Error
        message:
          type: string
          enum: [Token is not valid, Session expired]
```

2021-08-20 13:10 UTC, alanshaw commented on docs/.vuepress/public/schema.yml
> +            $ref: '#/components/schemas/upload'
Inlined in list endpoint response.

```suggestion
```

2021-08-20 16:29 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2021-08-20 16:29 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2021-08-20 16:29 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2021-08-20 16:30 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2021-08-20 16:30 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2021-08-20 16:32 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2021-08-20 16:32 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2021-08-20 16:32 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2021-08-20 16:32 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2021-08-20 16:32 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2021-08-20 16:32 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2021-08-20 16:32 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2021-08-20 16:32 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2021-08-20 16:33 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2021-08-20 20:24 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:24 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:24 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2021-08-20 20:25 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:25 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:25 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:25 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2021-08-20 20:25 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:26 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:27 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:27 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:27 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:27 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:27 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:29 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:29 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:45 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:45 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2021-08-20 20:45 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2021-08-20 20:45 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:46 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:46 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:46 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:46 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2021-08-20 20:46 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2021-08-20 20:46 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:46 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:47 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:47 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2021-08-20 20:48 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:48 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:48 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:49 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:49 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:49 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:50 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:50 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:50 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:50 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:51 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 503 (Service Unavailable):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:52 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:52 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:53 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:53 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2021-08-20 20:53 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2021-08-20 20:53 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2021-08-20 20:53 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 20:54 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link returned HTTP status code 404 (Not Found):
  https://ipfs.io
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-20 22:10 UTC, alanshaw requested changes
Aside from the few fixes this LGTM. I won't be around to fully approve so please merge asap when fixed. Would be good to sort the ordering per https://github.com/web3-storage/docs/pull/152/files#r692846546 but not blocking.

2021-08-20 22:10 UTC, alanshaw commented on docs/.vuepress/public/schema.yml
> +Requests to this endpoint have a maximum payload size of 100MB. To upload larger files, see the documentation for the `/car` endpoint.
Needs indent to validate.

```suggestion

        Requests to this endpoint have a maximum payload size of 100MB. To upload larger files, see the documentation for the `/car` endpoint.
```

2021-08-21 04:11 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-21 04:12 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-21 04:12 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-21 04:12 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-21 04:12 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-21 04:21 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain a fre...
                                             ^^^^^^^
  ```
- ‘put’ seems less likely than ‘out’.<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_PUT_OUT-->
  ```
  ... can be used as parameters when calling put(): name String. The name paramet...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... as parameters when calling put(): name String. The name parameter lets you ...
                                             ^^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...r IPFS path. For example, if you have a files directory like this: Using the...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...turn a CID for a directory containing a files subdirectory, like this: Howev...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ou do this instead: The contents of the files directory will be at the top l...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...ill be at the top level, instead of the files directory itself:  onRootCidRe...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ow) containing the queried CID. created String. The created property gives t...
                                             ^^^^^^
  ```
- Apostrophe might be missing. Did you mean “pin’s” (curly possessive apostrophe) or “pin's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...pload the same file(s). pins Array. The pins property is an array of Pin obj...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...operty is an array of Pin objects. Each Pin object represents a specific pee...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “deal’s” (curly possessive apostrophe) or “deal's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ... following structure:  deals Array. The deals property is an array of Deal o...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...perty is an array of Deal objects. Each Deal object represents a specific st...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...t with the following properties: before String. Specifies a date, in ISO 860...
                                             ^^^^^^
  ```

2021-08-21 04:22 UTC, johndmulhausen commented on docs/.vuepress/public/schema.yml
> +      requestBody:
I'm not sure what that tool is but it should be finding the description for CIDs based on `$ref: '#/components/schemas/CID'` being in the `schema` -- no need to override the great description that's there or to veer from using a single source of truth.

2021-08-21 04:23 UTC, merged