feat: add golang client to storage how-to
web3-storage/docs pull request #199
Opened 2021-10-25 21:13 UTC by yusefnapora

This adds the Go client to the storage how-to, courtesy of docusaurus's support for tab groups. I also added a very basic go client reference page that just links to the pkg.go.dev docs, just to have something to link to in the sidebar. 

We were using the route `/reference/client-library` to point to the js client docs, but now that we have more than one client that seems odd... so I moved the js docs to `/reference/js-client-library` and added a client-side redirect from `/reference/client-library` to `/reference/js-client-library`. The go placeholder reference page is at `/reference/go-client-library`, btw.

Closes #149

2021-10-29 18:42 UTC, filecorgi commented
- Image optimization came back clean!
- Docusaurus build was successful!

2021-11-03 11:07 UTC, alanshaw requested changes

2021-11-03 11:07 UTC, alanshaw commented on docs/how-tos/retrieve.md
> +The `Files` method returns an [`fs.File`](https://pkg.go.dev/io/fs#File) that may be either a single file or a directory, depending on the CID that you requested. To distinguish, you can check whethe
I think that's the shortest code path, and can be useful if you're going to read the directory.

It's maybe clearer/more explicit to use:

```go
info, err := f.Stat()
info.IsDir()
```

...and then do the type cast.

IDK up to you. I've not got strong feels.

Note: I believe that `File` objects you get back from the w3s client will always implement `ReadDirFile`. They don't have to though (any file you get from somewhere else does not have to implement it). You may be able to use the [`ReadDirFS`](https://pkg.go.dev/io/fs#ReadDirFS) interface to read a directory. e.g. the `os` package is a `ReadDirFS` implementation https://pkg.go.dev/os#ReadDir

2021-11-03 15:40 UTC, filecorgi commented
- Image optimization came back clean!
- Docusaurus build was successful!

2021-11-04 22:04 UTC, merged