Add query how-to
web3-storage/docs pull request #28
Opened 2021-07-20 20:30 UTC by yusefnapora

Here's a first pass at the Query how-to. @johndmulhausen how do you feel about the short field descriptions here, with more info in reference? That seems like a better place to describe the `pins` and `deals` objects in detail, IMO.

2021-07-20 20:33 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-tos/query.md`:
- The following link failed to connect:
  https://status.web3.storage
- The following link returned HTTP status code 404 (Not Found):
  https://staging.web3.storage/legal
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  When you store files with Web3.Storage, you receive a Content Identifier (CID)...
                                 ^^^^^^^
  ```
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... is valid and has been uploaded to Web3.Storage, the status method will retu...
                                             ^^^^^^^
  ```
- The conjunction “so that” does not have a comma in front.<!--CategoryID:PUNCTUATION, RuleID: SO_THAT_UNNECESSARY_COMMA-->
  ```
  ...D that was passed into the status method, so that you don't have to keep tra...
                                             ^^^^^^^^^
  ```
- Consider using “all the”.<!--CategoryID:REDUNDANCY, RuleID: ALL_OF_THE-->
  ```
  ...(DAG)  (opens new window) that contains all of the uploaded content. Note th...
                                             ^^^^^^^^^^
  ```
### `docs/how-tos/regenerate-api-key.md`:
- The following link failed to connect:
  https://status.web3.storage
- The following link returned HTTP status code 404 (Not Found):
  https://staging.web3.storage/legal

### `docs/how-tos/retrieve.md`:
- The following link failed to connect:
  https://status.web3.storage
- The following link returned HTTP status code 404 (Not Found):
  https://staging.web3.storage/legal
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... you have a client, you can call client.get, passing in a CID string:  The g...
                                             ^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...access to the retrieved IPFS data.  The files method returns an array of Web...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ...is guide, we'll use the gateway at dweb.link, but you can check the list of ...
                                             ^^^^
  ```
### `docs/how-tos/store.md`:
- The following link failed to connect:
  https://web3.storage/tokens/
- The following link failed to connect:
  https://web3.storage/files/
- The following link failed to connect:
  https://status.web3.storage
- The following link returned HTTP status code 404 (Not Found):
  https://staging.web3.storage/legal
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...APIs like fetch  (opens new window) and File  (opens new window). This guide...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ile objects manually: Unique file names Try to give each file a unique file ...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “file’s” (curly possessive apostrophe) or “file's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...one content archive, and linking to the files inside is much simpler if each...
                                             ^^^^^
  ```
- Consider using a more formal alternative to avoid the overused word “more”.<!--CategoryID:STYLE, RuleID: MORE_INFO-->
  ```
  ...the IPFS command line. You can also get more information about the status of...
                                             ^^^^^^^^^^^^^^^^
  ```

### `docs/reference/client-library.md`:
- The following link failed to connect:
  https://status.web3.storage
- The following link returned HTTP status code 404 (Not Found):
  https://staging.web3.storage/legal
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain an AP...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```

2021-07-20 22:05 UTC, alanshaw requested changes

2021-07-20 22:05 UTC, alanshaw commented on docs/how-tos/query.md
> +The `dagSize` field contains the size in bytes of the [Directed Acyclic Graph (DAG)][ipfs-docs-merkle-dag] that contains all of the uploaded content. Note that this is the size of the data that is tr
```suggestion
The `dagSize` field contains the size in bytes of the [Directed Acyclic Graph (DAG)][ipfs-docs-merkle-dag] that contains all of the uploaded content. Note that this is the size of the data that is transferred over the network to Web3.Storage during upload, and it will be slightly larger than the total size of the files on disk.
```

2021-07-21 12:56 UTC, johnnymatthews requested changes
Nice! Added a few suggestions through-out. But this is super easy to follow, and concise enough that it's not overwhelming!

2021-07-21 12:56 UTC, johnnymatthews commented on docs/how-tos/query.md
> +When you [store files with Web3.Storage][howto-store], you receive a Content Identifier (CID) that allows you to [retrieve it again][howto-retrieve]. The CID can also be used to query the service for
```suggestion
When you [store a file][howto-store] with Web3.Storage you receive a content identifier (CID) that you can use to [retrieve the file][howto-retrieve]. The CID can also be used to query the service for details about _how_ the data is stored on the [decentralized storage networks][concepts-decentralized-storage] that Web3.Storage uses under the hood.
```

2021-07-21 12:56 UTC, johnnymatthews commented on docs/how-tos/query.md
> +This guide will show how to use the [JavaScript client library][reference-js-client] to get information about content that's been uploaded to Web3.Storage.
```suggestion
This guide will show how to use the [JavaScript client library][reference-js-client] to get information about content on Web3.Storage.
```

2021-07-21 12:56 UTC, johnnymatthews commented on docs/how-tos/query.md
> +```bash
```suggestion
```shell
```

2021-07-21 12:56 UTC, johnnymatthews commented on docs/how-tos/query.md
> +```js
```suggestion
```javascript
```

2021-07-21 12:56 UTC, johnnymatthews commented on docs/how-tos/query.md
> +If you don't yet have an access token, head to the [Quickstart guide][quickstart]
```suggestion
:::tip Get an API token
If you don't yet have an access token, head to the [Quickstart guide to get one →][quickstart]
:::
```

2021-07-21 12:56 UTC, johnnymatthews commented on docs/how-tos/query.md
> +```js
```suggestion
```javascript
```

2021-07-21 12:56 UTC, johnnymatthews commented on docs/how-tos/query.md
> +The `dagSize` field contains the size in bytes of the [Directed Acyclic Graph (DAG)][ipfs-docs-merkle-dag] that contains all of the uploaded content. Note that this is the size of the data that is tr
```suggestion
The `dagSize` field contains the size in bytes of the [Directed Acyclic Graph (DAG)][ipfs-docs-merkle-dag] that contains all of the uploaded content. This is the size of the data that is transferred over the network to Web3.Storage during upload, and is slightly larger than the total size of the files on disk.
```

2021-07-21 12:56 UTC, johnnymatthews commented on docs/how-tos/query.md
> +The `pins` field contains an array of objects describing the IPFS nodes that have ["pinned"][ipfs-docs-pinning] the data, making it available for fast retrieval using the IPFS network.
```suggestion
The `pins` field contains an array of objects describing the IPFS nodes that have [pinned][ipfs-docs-pinning] the data, making it available for fast retrieval using the IPFS network.
```

2021-07-21 12:56 UTC, johnnymatthews commented on docs/how-tos/query.md
> +Finally, the `deals` field contains an array of objects describing the Filecoin storage providers that have made [storage deals][fil-docs-deals] committing them to store the data for an extended peri
```suggestion
Finally, the `deals` field contains an array of objects describing the Filecoin storage providers that have made [storage deals][fil-docs-deals]. These storage providers have now committed to storing the data for a period of time.
```

2021-07-21 15:45 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-tos/query.md`:
- The following link failed to connect:
  https://status.web3.storage
- The following link returned HTTP status code 404 (Not Found):
  https://staging.web3.storage/legal
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  When you store a file with Web3.Storage you receive a content identifier (CID) ...
                                  ^^^^^^^
  ```
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... is valid and has been uploaded to Web3.Storage, the status method will retu...
                                             ^^^^^^^
  ```
- The conjunction “so that” does not have a comma in front.<!--CategoryID:PUNCTUATION, RuleID: SO_THAT_UNNECESSARY_COMMA-->
  ```
  ...D that was passed into the status method, so that you don't have to keep tra...
                                             ^^^^^^^^^
  ```
- Consider using “all the”.<!--CategoryID:REDUNDANCY, RuleID: ALL_OF_THE-->
  ```
  ...(DAG)  (opens new window) that contains all of the uploaded content. This is...
                                             ^^^^^^^^^^
  ```
### `docs/how-tos/regenerate-api-key.md`:
- The following link failed to connect:
  https://status.web3.storage
- The following link returned HTTP status code 404 (Not Found):
  https://staging.web3.storage/legal

### `docs/how-tos/retrieve.md`:
- The following link failed to connect:
  https://status.web3.storage
- The following link returned HTTP status code 404 (Not Found):
  https://staging.web3.storage/legal
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... you have a client, you can call client.get, passing in a CID string:  The g...
                                             ^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...access to the retrieved IPFS data.  The files method returns an array of Web...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ...is guide, we'll use the gateway at dweb.link, but you can check the list of ...
                                             ^^^^
  ```
### `docs/how-tos/store.md`:
- The following link failed to connect:
  https://web3.storage/tokens/
- The following link failed to connect:
  https://web3.storage/files/
- The following link failed to connect:
  https://status.web3.storage
- The following link returned HTTP status code 404 (Not Found):
  https://staging.web3.storage/legal
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...APIs like fetch  (opens new window) and File  (opens new window). This guide...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ile objects manually: Unique file names Try to give each file a unique file ...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “file’s” (curly possessive apostrophe) or “file's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...one content archive, and linking to the files inside is much simpler if each...
                                             ^^^^^
  ```
- Consider using a more formal alternative to avoid the overused word “more”.<!--CategoryID:STYLE, RuleID: MORE_INFO-->
  ```
  ...the IPFS command line. You can also get more information about the status of...
                                             ^^^^^^^^^^^^^^^^
  ```

### `docs/reference/client-library.md`:
- The following link failed to connect:
  https://status.web3.storage
- The following link returned HTTP status code 404 (Not Found):
  https://staging.web3.storage/legal
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain an AP...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```

2021-07-21 15:57 UTC, johnnymatthews approved these changes

2021-07-21 20:11 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-tos/query.md`:
- The following link failed to connect:
  https://status.web3.storage
- The following link returned HTTP status code 404 (Not Found):
  https://staging.web3.storage/legal
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  When you store a file with Web3.Storage you receive a content identifier (CID) ...
                                  ^^^^^^^
  ```
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... is valid and has been uploaded to Web3.Storage, the status method will retu...
                                             ^^^^^^^
  ```
- The conjunction “so that” does not have a comma in front.<!--CategoryID:PUNCTUATION, RuleID: SO_THAT_UNNECESSARY_COMMA-->
  ```
  ...D that was passed into the status method, so that you don't have to keep tra...
                                             ^^^^^^^^^
  ```
- Consider using “all the”.<!--CategoryID:REDUNDANCY, RuleID: ALL_OF_THE-->
  ```
  ...(DAG)  (opens new window) that contains all of the uploaded content. This is...
                                             ^^^^^^^^^^
  ```
### `docs/how-tos/regenerate-api-key.md`:
- The following link failed to connect:
  https://status.web3.storage
- The following link returned HTTP status code 404 (Not Found):
  https://staging.web3.storage/legal

### `docs/how-tos/retrieve.md`:
- The following link failed to connect:
  https://status.web3.storage
- The following link returned HTTP status code 404 (Not Found):
  https://staging.web3.storage/legal
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... you have a client, you can call client.get, passing in a CID string:  The g...
                                             ^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...access to the retrieved IPFS data.  The files method returns an array of Web...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ...is guide, we'll use the gateway at dweb.link, but you can check the list of ...
                                             ^^^^
  ```
### `docs/how-tos/store.md`:
- The following link failed to connect:
  https://web3.storage/tokens/
- The following link failed to connect:
  https://web3.storage/files/
- The following link failed to connect:
  https://status.web3.storage
- The following link returned HTTP status code 404 (Not Found):
  https://staging.web3.storage/legal
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...APIs like fetch  (opens new window) and File  (opens new window). This guide...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ile objects manually: Unique file names Try to give each file a unique file ...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “file’s” (curly possessive apostrophe) or “file's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...one content archive, and linking to the files inside is much simpler if each...
                                             ^^^^^
  ```
- Consider using a more formal alternative to avoid the overused word “more”.<!--CategoryID:STYLE, RuleID: MORE_INFO-->
  ```
  ...the IPFS command line. You can also get more information about the status of...
                                             ^^^^^^^^^^^^^^^^
  ```

### `docs/reference/client-library.md`:
- The following link failed to connect:
  https://status.web3.storage
- The following link returned HTTP status code 404 (Not Found):
  https://staging.web3.storage/legal
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain an AP...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```

2021-07-21 20:14 UTC, merged