Add status() docs to Client JS reference
web3-storage/docs pull request #30
Opened 2021-07-20 20:40 UTC by johndmulhausen

What it says on the tin

2021-07-20 20:41 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-tos/regenerate-api-key.md`:
- The following link failed to connect:
  https://status.web3.storage
- The following link returned HTTP status code 404 (Not Found):
  https://staging.web3.storage/legal

### `docs/how-tos/retrieve.md`:
- The following link failed to connect:
  https://status.web3.storage
- The following link returned HTTP status code 404 (Not Found):
  https://staging.web3.storage/legal
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... you have a client, you can call client.get, passing in a CID string:  The g...
                                             ^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...access to the retrieved IPFS data.  The files method returns an array of Web...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ...is guide, we'll use the gateway at dweb.link, but you can check the list of ...
                                             ^^^^
  ```
### `docs/how-tos/store.md`:
- The following link failed to connect:
  https://web3.storage/tokens/
- The following link failed to connect:
  https://web3.storage/files/
- The following link failed to connect:
  https://status.web3.storage
- The following link returned HTTP status code 404 (Not Found):
  https://staging.web3.storage/legal
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...APIs like fetch  (opens new window) and File  (opens new window). This guide...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ile objects manually: Unique file names Try to give each file a unique file ...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “file’s” (curly possessive apostrophe) or “file's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...one content archive, and linking to the files inside is much simpler if each...
                                             ^^^^^
  ```
- Consider using a more formal alternative to avoid the overused word “more”.<!--CategoryID:STYLE, RuleID: MORE_INFO-->
  ```
  ...the IPFS command line. You can also get more information about the status of...
                                             ^^^^^^^^^^^^^^^^
  ```

### `docs/reference/client-library.md`:
- The following link failed to connect:
  https://status.web3.storage
- The following link returned HTTP status code 404 (Not Found):
  https://staging.web3.storage/legal
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain an AP...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...etwork is storing your data. Using this information you can enumerate peers ...
                                             ^^^^^^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```

2021-07-20 22:13 UTC, alanshaw commented on docs/reference/client-library.md
> +Retrieve metadata about your file by using the `status()` method, supplying the CID of the file you are interested in. This metadata includes the creation date and size, as well as details about how
```suggestion
Retrieve metadata about your file by using the `status()` method, supplying the CID of the file you are interested in. This metadata includes the creation date and size, as well as details about how the network is storing your data. Using this information you can enumerate peers on the InterPlanetary File System (IPFS) network that are pinning the data, and Filecoin storage providers that have accepted deals to store the data.
```

2021-07-20 22:13 UTC, alanshaw commented on docs/reference/client-library.md
> +| 2 | `{options}` | Optional. A JSON object whose properties define certain Web3.Storage options and metadata about the files being uploaded. See below for more details. |
Not JSON, just a plain object.

```suggestion
| 2 | `{options}` | Optional. An object whose properties define certain Web3.Storage options and metadata about the files being uploaded. See below for more details. |
```

2021-07-20 22:13 UTC, alanshaw commented on docs/reference/client-library.md
>    onStoredChunk: handlerFunction
You can find good descriptions of these options here: https://github.com/web3-storage/web3.storage/blob/20d02fc22725de825cc2a4f773b40e0d1f8a6a68/packages/client/src/lib/interface.ts#L62

2021-07-21 13:58 UTC, johnnymatthews reviewed
See comment https://github.com/web3-storage/docs/pull/30/files#r673995355

2021-07-21 16:04 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-tos/regenerate-api-key.md`:
- The following link failed to connect:
  https://status.web3.storage
- The following link returned HTTP status code 404 (Not Found):
  https://staging.web3.storage/legal

### `docs/how-tos/retrieve.md`:
- The following link failed to connect:
  https://status.web3.storage
- The following link returned HTTP status code 404 (Not Found):
  https://staging.web3.storage/legal
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... you have a client, you can call client.get, passing in a CID string:  The g...
                                             ^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...access to the retrieved IPFS data.  The files method returns an array of Web...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ...is guide, we'll use the gateway at dweb.link, but you can check the list of ...
                                             ^^^^
  ```
### `docs/how-tos/store.md`:
- The following link failed to connect:
  https://web3.storage/tokens/
- The following link failed to connect:
  https://web3.storage/files/
- The following link failed to connect:
  https://status.web3.storage
- The following link returned HTTP status code 404 (Not Found):
  https://staging.web3.storage/legal
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...APIs like fetch  (opens new window) and File  (opens new window). This guide...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ile objects manually: Unique file names Try to give each file a unique file ...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “file’s” (curly possessive apostrophe) or “file's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...one content archive, and linking to the files inside is much simpler if each...
                                             ^^^^^
  ```
- Consider using a more formal alternative to avoid the overused word “more”.<!--CategoryID:STYLE, RuleID: MORE_INFO-->
  ```
  ...the IPFS command line. You can also get more information about the status of...
                                             ^^^^^^^^^^^^^^^^
  ```

### `docs/reference/client-library.md`:
- The following link failed to connect:
  https://status.web3.storage
- The following link returned HTTP status code 404 (Not Found):
  https://staging.web3.storage/legal
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain an AP...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...etwork is storing your data. Using this information you can enumerate peers ...
                                             ^^^^^^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```

2021-07-21 16:06 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-tos/regenerate-api-key.md`:
- The following link failed to connect:
  https://status.web3.storage
- The following link returned HTTP status code 404 (Not Found):
  https://staging.web3.storage/legal

### `docs/how-tos/retrieve.md`:
- The following link failed to connect:
  https://status.web3.storage
- The following link returned HTTP status code 404 (Not Found):
  https://staging.web3.storage/legal
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... you have a client, you can call client.get, passing in a CID string:  The g...
                                             ^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...access to the retrieved IPFS data.  The files method returns an array of Web...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ...is guide, we'll use the gateway at dweb.link, but you can check the list of ...
                                             ^^^^
  ```
### `docs/how-tos/store.md`:
- The following link failed to connect:
  https://web3.storage/tokens/
- The following link failed to connect:
  https://web3.storage/files/
- The following link failed to connect:
  https://status.web3.storage
- The following link returned HTTP status code 404 (Not Found):
  https://staging.web3.storage/legal
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...APIs like fetch  (opens new window) and File  (opens new window). This guide...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ile objects manually: Unique file names Try to give each file a unique file ...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “file’s” (curly possessive apostrophe) or “file's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...one content archive, and linking to the files inside is much simpler if each...
                                             ^^^^^
  ```
- Consider using a more formal alternative to avoid the overused word “more”.<!--CategoryID:STYLE, RuleID: MORE_INFO-->
  ```
  ...the IPFS command line. You can also get more information about the status of...
                                             ^^^^^^^^^^^^^^^^
  ```

### `docs/reference/client-library.md`:
- The following link failed to connect:
  https://status.web3.storage
- The following link returned HTTP status code 404 (Not Found):
  https://staging.web3.storage/legal
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain an AP...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...etwork is storing your data. Using this information you can enumerate peers ...
                                             ^^^^^^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```

2021-07-21 16:10 UTC, yusefnapora commented
@johndmulhausen / @johnnymatthews  How do you guys feel about using a table for the `Pin` and `Deal` object fields?

<img width="875" alt="Screen Shot 2021-07-21 at 12 02 48 PM" src="https://user-images.githubusercontent.com/678715/126521650-24ab9a30-d930-4fc7-8b96-8d0137efb0c9.png">

I think it's a bit easier to scan through, but maybe that's just me :)

2021-07-21 20:04 UTC, yusefnapora requested changes

2021-07-21 20:04 UTC, yusefnapora commented on docs/reference/client-library.md
> +The `status()` method returns a `{Status}` object that contains the metadata for your object's storage deal on the Web3.Storage network. This object will have the following properties:
I think we should mention that it will return `undefined` if the CID isn't found.

2021-07-21 21:11 UTC, olizilla commented on docs/reference/client-library.md
> +The `status()` method returns a `{Status}` object that contains the metadata for your object's storage deal on the Web3.Storage network. This object will have the following properties:
Aye! I'm not sure of the ergonomics of that decision tho. We could just have it throw on anything other than a Cid that we were able to get a status for. What do you think?

2021-07-22 04:55 UTC, johndmulhausen commented on docs/reference/client-library.md
> +The `status()` method returns a `{Status}` object that contains the metadata for your object's storage deal on the Web3.Storage network. This object will have the following properties:
@olizilla I feel like returning an object with really obvious "not found" values might be more merciful given that `undefined` will almost surely throw people's code into an exception state, but hey.

2021-07-22 05:11 UTC, johndmulhausen commented on docs/reference/client-library.md
>    onStoredChunk: handlerFunction
Just a bit further down the parameters are covered in much better detail so I removed this bit

2021-07-22 05:16 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link failed to connect:
  https://status.web3.storage
- The following link returned HTTP status code 404 (Not Found):
  https://staging.web3.storage/legal
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain an AP...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...etwork is storing your data. Using this information you can enumerate peers ...
                                             ^^^^^^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```

2021-07-22 05:19 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link failed to connect:
  https://status.web3.storage
- The following link returned HTTP status code 404 (Not Found):
  https://staging.web3.storage/legal
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain an AP...
                                             ^^^^^^^
  ```
- ‘your’ (possessive pronoun) seems less likely than ‘you’ (personal pronoun).<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_YOUR_YOU-->
  ```
  ...ties that can be used as parameters for your put() operation:  String. The n...
                                             ^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...etwork is storing your data. Using this information you can enumerate peers ...
                                             ^^^^^^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```

2021-07-22 05:21 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link failed to connect:
  https://status.web3.storage
- The following link returned HTTP status code 404 (Not Found):
  https://staging.web3.storage/legal
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain an AP...
                                             ^^^^^^^
  ```
- ‘your’ (possessive pronoun) seems less likely than ‘you’ (personal pronoun).<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_YOUR_YOU-->
  ```
  ...ties that can be used as parameters for your put() operation:  String. The n...
                                             ^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...etwork is storing your data. Using this information you can enumerate peers ...
                                             ^^^^^^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```

2021-07-22 05:22 UTC, johndmulhausen commented
> @johndmulhausen / @johnnymatthews How do you guys feel about using a table for the `Pin` and `Deal` object fields?
> 
> <img alt="Screen Shot 2021-07-21 at 12 02 48 PM" width="875" src="https://user-images.githubusercontent.com/678715/126521650-24ab9a30-d930-4fc7-8b96-8d0137efb0c9.png">
> 
> I think it's a bit easier to scan through, but maybe that's just me :)

Just confirming that @johnnymatthews , @yusefnapora , and I all had a great chat about this issue and decided to leave this in object form as it just scans *on the page* really well and does a better job visually representing the structure of `Deal` and `Pin` objects.

2021-07-22 05:25 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link failed to connect:
  https://status.web3.storage
- The following link returned HTTP status code 404 (Not Found):
  https://staging.web3.storage/legal
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain an AP...
                                             ^^^^^^^
  ```
- ‘your’ (possessive pronoun) seems less likely than ‘you’ (personal pronoun).<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_YOUR_YOU-->
  ```
  ...ties that can be used as parameters for your put() operation:  String. The n...
                                             ^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```

2021-07-22 15:35 UTC, johnnymatthews approved these changes

2021-07-22 17:36 UTC, yusefnapora commented on docs/reference/client-library.md
> +The `status()` method returns a `{Status}` object that contains the metadata for your object's storage deal on the Web3.Storage network. This object will have the following properties:
I like the idea of a "not found" response object a bit better than throwing, but either way could work. For now it seems worth documenting the current behavior & we can update if the API changes.

2021-07-22 17:49 UTC, olizilla commented on docs/reference/client-library.md
> +The `status()` method returns a `{Status}` object that contains the metadata for your object's storage deal on the Web3.Storage network. This object will have the following properties:
For context, I took my cues from the behaviour of `Map.get()` here. It returns `undefined` if you ask for a thing that is not in it. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/get

2021-07-22 18:55 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/client-library.md`:
- The following link failed to connect:
  https://status.web3.storage
- The following link returned HTTP status code 404 (Not Found):
  https://staging.web3.storage/legal
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain an AP...
                                             ^^^^^^^
  ```
- ‘your’ (possessive pronoun) seems less likely than ‘you’ (personal pronoun).<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_YOUR_YOU-->
  ```
  ...ties that can be used as parameters for your put() operation:  String. The n...
                                             ^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```

2021-07-22 18:57 UTC, johndmulhausen commented on docs/reference/client-library.md
> +The `status()` method returns a `{Status}` object that contains the metadata for your object's storage deal on the Web3.Storage network. This object will have the following properties:
Agreed on doc'ing current behavior. Added details for `undefined` for `status()` and `get()`. 

I ain't mad at the method returning `undefined` -- stark as it is. I just have a hunch that a "not found" response object with a helpful message embedded is somewhat more akin to, for instance, an HTTP status code of 500 with details in the payload. Food for thought, anyway. :)

2021-07-22 19:31 UTC, yusefnapora approved these changes

2021-07-22 19:51 UTC, merged