Add Contact Us page & update footer links
web3-storage/docs pull request #33
Opened 2021-07-21 19:00 UTC by terichadbourne

This PR adds a basic Contact Us page at JV's request, proposed to live at /community/contact-us/. This new page is where we'll direct to from the footer "Join us on Slack" to avoid the challenge of getting people signed onto Filecoin Slack and directed to the right channel simultaneously. 

It also corrects a few footer links given newfound clarity about where they should lead. 

Todo: 

- [ ] Update mailto link. 
- [ ]TBC: Change terms link from /terms to /about#something in terms end up inside of the about page.

2021-07-21 19:01 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/community/contact-us.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://filecoin.io/slack
- The following link returned HTTP status code 302 (Found):
  https://github.com/web3-storage/web3.storage/issues/new/choose
- The following link failed to connect:
  https://status.web3.storage
- The following link returned HTTP status code 302 (Found):
  https://staging.web3.storage/terms
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...e channel on Slack!  (opens new window) Found a bug or have a feature reques...
                                             ^^^^^
  ```

2021-07-21 19:15 UTC, jessicaschilling requested changes
Thanks @terichadbourne - made some suggestions for clarity and better pathing.

2021-07-21 19:15 UTC, jessicaschilling commented on docs/community/contact-us.md
> +title: Contact Us
```suggestion
title: Help & support
```
for consistency with other properties, and for sentence case rather than title case

2021-07-21 19:15 UTC, jessicaschilling commented on docs/community/contact-us.md
> +If you're having trouble with the Web3.Storage service, we're here to help.
```suggestion
If you're having trouble with the Web3.Storage service, or just want to get help and support from the global Web3 developer community, here's where to start.
```

2021-07-21 19:15 UTC, jessicaschilling commented on docs/community/contact-us.md
> +**Have a question?**
```suggestion
## Questions and community discussion
```

2021-07-21 19:15 UTC, jessicaschilling commented on docs/community/contact-us.md
> +Join us in the **#web3-storage** channel on [Slack!](https://filecoin.io/slack)
```suggestion
Have a question? Want to discuss problems, opportunities, or ideas? Join your peers in the Web3 developer community in the **#web3-storage** channel on [Slack.](https://filecoin.io/slack)
```

2021-07-21 19:15 UTC, jessicaschilling commented on docs/community/contact-us.md
> +**Found a bug or have a feature request?**
```suggestion
## Bug reports or feature requests
```

2021-07-21 19:15 UTC, jessicaschilling commented on docs/community/contact-us.md
> +[File an issue!](https://github.com/web3-storage/web3.storage/issues/new/choose)
```suggestion
Found a bug or have a feature request? File an issue and make your voice heard.
- [File an issue for Web3.Storage docs](https://github.com/web3-storage/docs/issues/new/choose)
- [File an issue for Web3.Storage itself](https://github.com/web3-storage/web3.storage/issues/new/choose)
```

2021-07-21 19:15 UTC, jessicaschilling commented on docs/community/contact-us.md
> +**Need more storage?**
```suggestion
## Request more storage space
```

2021-07-21 19:15 UTC, jessicaschilling commented on docs/community/contact-us.md
> +[Shoot us a note.](mailto:web3storage@protocol.ai)
```suggestion
Need more storage? [Shoot us a note.](mailto:web3storage@protocol.ai)
```

2021-07-21 19:15 UTC, jessicaschilling commented on docs/.vuepress/theme/layouts/GlobalLayout.vue
> +                href="/community/contact-us/"
```suggestion
                href="/community/contact-us#questions-and-community-discussion"
```
Direct link to the relevant header

2021-07-21 19:15 UTC, jessicaschilling commented on docs/.vuepress/theme/layouts/GlobalLayout.vue
>                  target="_blank"
```suggestion
```

2021-07-21 19:15 UTC, jessicaschilling commented on docs/.vuepress/theme/layouts/GlobalLayout.vue
>                  rel="noopener noreferrer"
```suggestion
```

2021-07-21 19:15 UTC, jessicaschilling commented on docs/.vuepress/theme/layouts/GlobalLayout.vue
> +                href="https://github.com/web3-storage/web3.storage/issues/new/choose"
```suggestion
                href="/community/contact-us#bug-reports-and-feature-requests"
```

2021-07-21 19:15 UTC, jessicaschilling commented on docs/.vuepress/theme/layouts/GlobalLayout.vue
>                  target="_blank"
```suggestion
```

2021-07-21 19:15 UTC, jessicaschilling commented on docs/.vuepress/theme/layouts/GlobalLayout.vue
>                  rel="noopener noreferrer"
```suggestion
```

2021-07-21 19:48 UTC, johnnymatthews approved these changes
The docs aren't the place for a _Contact us_ page, but @jessicaschilling's changes address my concerns - making this page into a _how to get help and stuff_ instead of a _here's our email address_ page.

In short, I'm happy.

2021-07-21 19:58 UTC, terichadbourne commented on docs/.vuepress/theme/layouts/GlobalLayout.vue
> +                href="https://github.com/web3-storage/web3.storage/issues/new/choose"
@jessicaschilling Just confirming you're suggesting this change out of a concern that people will click the "open an issue" link when they want to change the docs, not the API or main website, and you want the opportunity to split the traffic? If they're on the docs site, I would expect them to see the callout about how to change or file an issue about the specific page they're on before reaching the footer itself. Are you also proposing this flow from the main website (to docs to split options instead of directly to new issues for main website)?

2021-07-21 20:03 UTC, terichadbourne commented on docs/.vuepress/theme/layouts/GlobalLayout.vue
> +                href="/community/contact-us/"
@jessicaschilling I did try the layout with headers but didn't feel there was enough content to justify it. I'll try setting it up your suggested way with the new content and see if it feels less silly than when I did it. 😂
![image](https://user-images.githubusercontent.com/19171465/126552337-7d9c4bb9-d0ee-46ba-a803-8f50e2b41682.png)

Will circle back and fix the link since the `contact-us` portion won't be correct but I need to play with what the asterisk causes to happen.

2021-07-21 20:05 UTC, terichadbourne commented on docs/community/contact-us.md
> +Join us in the **#web3-storage** channel on [Slack!](https://filecoin.io/slack)
@jessicaschilling I'm in support of adding additional context here, but I didn't think the channel was for discussing Web3 general stuff, but rather for discussing the Web3.Storage service and how to use it. @jnthnvctr what's your take?

2021-07-21 20:06 UTC, terichadbourne commented on docs/community/contact-us.md
> +[File an issue!](https://github.com/web3-storage/web3.storage/issues/new/choose)
@jessicaschilling Would you be opposed to swapping the order to put service issues above docs issues? In which case we'd describe it as "the Web3.Storage service"?

2021-07-21 20:08 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/community/contact-us.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://filecoin.io/slack
- The following link returned HTTP status code 302 (Found):
  https://github.com/web3-storage/web3.storage/issues/new/choose
- The following link failed to connect:
  https://status.web3.storage
- The following link returned HTTP status code 302 (Found):
  https://staging.web3.storage/terms

2021-07-21 20:16 UTC, jessicaschilling commented on docs/community/contact-us.md
> +[File an issue!](https://github.com/web3-storage/web3.storage/issues/new/choose)
@terichadbourne sure, that makes sense!

2021-07-21 20:17 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/community/help-and-support.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://filecoin.io/slack
- The following link returned HTTP status code 302 (Found):
  https://github.com/web3-storage/web3.storage/issues/new/choose
- The following link returned HTTP status code 302 (Found):
  https://staging.web3.storage/terms

2021-07-21 20:19 UTC, jessicaschilling commented on docs/community/contact-us.md
> +Join us in the **#web3-storage** channel on [Slack!](https://filecoin.io/slack)
@terichadbourne Maybe just this then?
`Have a question about using Web3.Storage? Want to discuss problems, opportunities, or ideas for integrating Web3.Storage into your project or product? Join your peers in the developer community in the **#web3-storage** channel on [Slack.](https://filecoin.io/slack)`

2021-07-21 20:20 UTC, jessicaschilling commented on docs/.vuepress/theme/layouts/GlobalLayout.vue
> +                href="https://github.com/web3-storage/web3.storage/issues/new/choose"
@terichadbourne That's exactly my concern 😊 
I don't think you need to change the footer link destination on the main web3.storage site itself ... but I can see situations when someone's in the docs because they're having a problem with the service, and then decide they want to file an issue against the service.

2021-07-21 20:26 UTC, terichadbourne commented on docs/community/contact-us.md
> +Join us in the **#web3-storage** channel on [Slack!](https://filecoin.io/slack)
Love it!

2021-07-21 20:55 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/community/help-and-support.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://filecoin.io/slack
- The following link returned HTTP status code 302 (Found):
  https://github.com/web3-storage/web3.storage/issues/new/choose
- The following link returned HTTP status code 302 (Found):
  https://staging.web3.storage/terms
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... channel on Slack.  (opens new window)  Found a bug or have a feature reques...
                                             ^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...eb3.Storage service  (opens new window) File an issue for the Web3.Storage d...
                                             ^^^^
  ```

2021-07-21 20:59 UTC, terichadbourne commented
I believe I've now made all of @jessicaschilling's suggested updates, gotten the mailto link working, and gotten the footer links correct in the sense that they correctly indicate where I want them to go. However, **2 links aren't formatted properly yet**. 

@jessicaschilling @johnnymatthews Could one of you help me figure this link thing out? I’ve tried two things unsuccessfully to link from the footer (which could be accessed from any page in docs) to a specific spot on the new page:
- This didn’t work because it just adds the ending to the existing URL, duplicating the community/help-and-support twice if I’m already on the right page: 
```js
href=“/community/help-and-support/#questions-and-community-discussion”
```
- This (which is how it is currently) didn’t work because it goes to the staging domain instead of the localhost preview I’m on, so I can’t test it: 
```js
:href=“`${$site.themeConfig.domain}/community/help-and-support/#questions-and-community-discussion`”
```

I think we can merge after those links are fixed, but we'll need to circle back right before launch based on where the terms actually end up living and update the footer link accordingly.

2021-07-21 21:02 UTC, jessicaschilling commented
@terichadbourne I'd just use the latter option, honestly, and paste in the localhost info in your browser tab instead of the variable stuff to test it. That said, @zebateira might have a prettier idea.

2021-07-21 21:05 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/community/help-and-support.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://filecoin.io/slack
- The following link returned HTTP status code 302 (Found):
  https://github.com/web3-storage/web3.storage/issues/new/choose
- The following link returned HTTP status code 302 (Found):
  https://staging.web3.storage/terms
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... channel on Slack.  (opens new window)  Found a bug or have a feature reques...
                                             ^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...eb3.Storage service  (opens new window) File an issue for the Web3.Storage d...
                                             ^^^^
  ```

2021-07-22 10:55 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/community/help-and-support.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://filecoin.io/slack
- The following link returned HTTP status code 302 (Found):
  https://github.com/web3-storage/web3.storage/issues/new/choose
- The following link returned HTTP status code 302 (Found):
  https://staging.web3.storage/terms
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... channel on Slack.  (opens new window)  Found a bug or have a feature reques...
                                             ^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...eb3.Storage service  (opens new window) File an issue for the Web3.Storage d...
                                             ^^^^
  ```

2021-07-22 10:59 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

### `docs/community/help-and-support.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://filecoin.io/slack
- The following link returned HTTP status code 302 (Found):
  https://github.com/web3-storage/web3.storage/issues/new/choose
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... channel on Slack.  (opens new window)  Found a bug or have a feature reques...
                                             ^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...eb3.Storage service  (opens new window) File an issue for the Web3.Storage d...
                                             ^^^^
  ```

- Check of `docs/concepts/content-addressing.md` came back clean!
- Check of `docs/concepts/decentralized-storage.md` came back clean!
### `docs/concepts/example-topic.md`:
- The following link returned HTTP status code 403 (Forbidden):
  https://a16z.com/2019/11/08/crypto-glossary/
- Should there be a question mark at the end of this sentence?<!--CategoryID:PUNCTUATION, RuleID: MISSING_QUESTION_MARK2-->
  ```
  ... who'd like to improve the docs for Web3.Storage? Help write this page!     ...
                                             ^
  ```
- Check of `docs/how-tos/query.md` came back clean!
### `docs/how-tos/store.md`:
- The following link failed to connect:
  https://web3.storage/tokens/
- The following link failed to connect:
  https://web3.storage/files/
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...APIs like fetch  (opens new window) and File  (opens new window). This guide...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...the browser runtime. On node.js, import File from the web3.storage package a...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ile objects manually: Unique file names Try to give each file a unique file ...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “file’s” (curly possessive apostrophe) or “file's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...one content archive, and linking to the files inside is much simpler if each...
                                             ^^^^^
  ```
- Consider using a more formal alternative to avoid the overused word “more”.<!--CategoryID:STYLE, RuleID: MORE_INFO-->
  ```
  ...the IPFS command line. You can also get more information about the status of...
                                             ^^^^^^^^^^^^^^^^
  ```
### `docs/reference/client-library.md`:
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain an AP...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```

2021-07-22 11:03 UTC, zebateira commented
@terichadbourne @jessicaschilling I moved the footer links to the config so all nav, sidebar and footer links are together.

Regarding the two links that were not working, the first approach works with `<RouterLink />` instead of `a`. This is inferred from the links so no need to worry about that now.

Let me know if everything looks good now.

2021-07-22 11:09 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

### `docs/community/help-and-support.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://filecoin.io/slack
- The following link returned HTTP status code 302 (Found):
  https://github.com/web3-storage/web3.storage/issues/new/choose
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... channel on Slack.  (opens new window)  Found a bug or have a feature reques...
                                             ^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...eb3.Storage service  (opens new window) File an issue for the Web3.Storage d...
                                             ^^^^
  ```

- Check of `docs/concepts/content-addressing.md` came back clean!
- Check of `docs/concepts/decentralized-storage.md` came back clean!
### `docs/concepts/example-topic.md`:
- The following link returned HTTP status code 403 (Forbidden):
  https://a16z.com/2019/11/08/crypto-glossary/
- Should there be a question mark at the end of this sentence?<!--CategoryID:PUNCTUATION, RuleID: MISSING_QUESTION_MARK2-->
  ```
  ... who'd like to improve the docs for Web3.Storage? Help write this page!     ...
                                             ^
  ```
- Check of `docs/how-tos/query.md` came back clean!
### `docs/how-tos/store.md`:
- The following link failed to connect:
  https://web3.storage/tokens/
- The following link failed to connect:
  https://web3.storage/files/
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...APIs like fetch  (opens new window) and File  (opens new window). This guide...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...the browser runtime. On node.js, import File from the web3.storage package a...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ile objects manually: Unique file names Try to give each file a unique file ...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “file’s” (curly possessive apostrophe) or “file's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...one content archive, and linking to the files inside is much simpler if each...
                                             ^^^^^
  ```
- Consider using a more formal alternative to avoid the overused word “more”.<!--CategoryID:STYLE, RuleID: MORE_INFO-->
  ```
  ...the IPFS command line. You can also get more information about the status of...
                                             ^^^^^^^^^^^^^^^^
  ```
### `docs/reference/client-library.md`:
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain an AP...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```

2021-07-22 14:12 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

### `docs/community/help-and-support.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://filecoin.io/slack
- The following link returned HTTP status code 302 (Found):
  https://github.com/web3-storage/web3.storage/issues/new/choose
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... channel on Slack.  (opens new window)  Found a bug or have a feature reques...
                                             ^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...eb3.Storage service  (opens new window) File an issue for the Web3.Storage d...
                                             ^^^^
  ```

- Check of `docs/concepts/content-addressing.md` came back clean!
- Check of `docs/concepts/decentralized-storage.md` came back clean!
### `docs/concepts/example-topic.md`:
- The following link returned HTTP status code 403 (Forbidden):
  https://a16z.com/2019/11/08/crypto-glossary/
- Should there be a question mark at the end of this sentence?<!--CategoryID:PUNCTUATION, RuleID: MISSING_QUESTION_MARK2-->
  ```
  ... who'd like to improve the docs for Web3.Storage? Help write this page!     ...
                                             ^
  ```
- Check of `docs/how-tos/query.md` came back clean!
### `docs/how-tos/store.md`:
- The following link failed to connect:
  https://web3.storage/profile/
- The following link failed to connect:
  https://web3.storage/files/
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...APIs like fetch  (opens new window) and File  (opens new window). This guide...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...the browser runtime. On node.js, import File from the web3.storage package a...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ile objects manually: Unique file names Try to give each file a unique file ...
                                             ^^^
  ```
- Apostrophe might be missing. Did you mean “file’s” (curly possessive apostrophe) or “file's” (straight possessive apostrophe)? (Some terms such as “farmers’ market” have a possessive apostrophe after the first noun.)<!--CategoryID:TYPOGRAPHY, RuleID: THE_NNS_NN_IS-->
  ```
  ...one content archive, and linking to the files inside is much simpler if each...
                                             ^^^^^
  ```
- Consider using a more formal alternative to avoid the overused word “more”.<!--CategoryID:STYLE, RuleID: MORE_INFO-->
  ```
  ...the IPFS command line. You can also get more information about the status of...
                                             ^^^^^^^^^^^^^^^^
  ```
### `docs/reference/client-library.md`:
- Possibly missing preposition found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_IN-->
  ```
  ... the JavaScript client library for Web3.Storage, you must first obtain an AP...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...tional order. Number Type Description 1 string A string containing the CID o...
                                             ^^^^^^
  ```

2021-07-22 14:13 UTC, merged