WIP - Store howto
web3-storage/docs pull request #9
Opened 2021-07-07 19:16 UTC by yusefnapora

This is a first draft of the storage how-to guide. It's still missing an intro paragraph and could use some massaging still in a few places.

There might be some overlap with the reference stuff @johndmulhausen is working on - we can pull the "Upload options" section out of here if so, maybe.

2021-07-07 19:17 UTC, filecorgi commented
- I optimized some images for you! See the commit with the comment `Automatically optimized images [ci skip].` in this PR for details.
- Vuepress build was successful!

2021-07-07 19:22 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!

2021-07-07 21:24 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-tos/retrieve.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu/not-distributed.jpg
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ...age client TODO: show how to use client.get # Using an IPFS HTTP gateway You...
                                             ^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ... to use client.get # Using an IPFS HTTP gateway You can easily fetch any dat...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ...is guide, we'll use the gateway at dweb.link, but you can check the list of ...
                                             ^^^^
  ```

2021-07-07 21:27 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-tos/retrieve.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu/not-distributed.jpg
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ...age client TODO: show how to use client.get # Using an IPFS HTTP gateway You...
                                             ^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ... to use client.get # Using an IPFS HTTP gateway You can easily fetch any dat...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ...is guide, we'll use the gateway at dweb.link, but you can check the list of ...
                                             ^^^^
  ```

2021-07-08 16:25 UTC, johnnymatthews requested changes
Nice! This is super clear, and pretty simple to follow. Should do nicely!

2021-07-08 16:25 UTC, johnnymatthews commented on docs/how-tos/retrieve.md
> +TODO: intro paragraph
You gonna add something in here later? Or did you forget to delete it

```suggestion
<!-- TODO: intro paragraph -->
```

2021-07-08 16:25 UTC, johnnymatthews commented on docs/how-tos/retrieve.md
> +TODO: show how to use `client.get`
```suggestion
<!-- 
## Using the Web3.Storage client

TODO: show how to use `client.get`
-->
```

2021-07-08 16:25 UTC, johnnymatthews commented on docs/how-tos/retrieve.md
> +TODO: show how to use `client.get`
Probably best to hide this stuff until we've got content for it. Just on the off chance that someone stumbles on the site.

2021-07-08 16:25 UTC, johnnymatthews commented on docs/how-tos/retrieve.md
> +When you [store data using the Web3.Storage client][howto-store], the `put` method returns an [IPFS Content ID][ipfs-docs-cid] string. That CID points to an IPFS directory that contains all the files
```suggestion
When you [store data using the Web3.Storage client][howto-store], the `put` method returns an [IPFS content identifier (CID)][ipfs-docs-cid] string. That CID points to an IPFS directory that contains all the files passed in to the `put` method.
```

2021-07-08 16:25 UTC, johnnymatthews commented on docs/how-tos/retrieve.md
> +```
````suggestion
To get the whole bundle and save it to a directory, run:

```shell
ipfs get bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu
```

If you want to get a specific file out of the bundle, add the filename onto the end of the `ipfs get bafybie...` command:

```shell
ipfs get bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu/youareanonsense.jpg
```
````

2021-07-08 16:25 UTC, johnnymatthews commented on docs/how-tos/store.md
> +Web3.Storage provides a simple interface for storing data, inspired by familiar web APIs like [`fetch`][mdn-fetch] and [`File`][mdn-file]. This how-to guide will show how to use the Web3.Storage clie
```suggestion
Web3.Storage provides a simple interface for storing data, inspired by familiar web APIs like [`fetch`][mdn-fetch] and [`File`][mdn-file]. This guide will show how to use the Web3.Storage client to make your data available on the decentralized IPFS network, with persistent long-term storage provided by Filecoin.
```

2021-07-08 16:25 UTC, johnnymatthews commented on docs/how-tos/store.md
> +This guide focuses on the [JavaScript client library][reference-js] , which is the simplest way to use Web3.Storage. If you're using another language, see the [HTTP API reference][reference-http] for
```suggestion
We'll focus on the [JavaScript client library][reference-js] , which is the simplest way to use Web3.Storage. If you're using another language, see the [HTTP API reference][reference-http] for details on working with the underlying HTTP API.
```

2021-07-08 16:25 UTC, johnnymatthews commented on docs/how-tos/store.md
> +```
```suggestion
:::tip Running a browser environment
If you're running in a browser environment, you'll also need the `web3-file` package, which extends the [Web File API][mdn-file] to include file paths and other metadata required by the Web3.Storage API.

```bash
npm install web3-file
```
:::
```

2021-07-08 16:25 UTC, johnnymatthews commented on docs/how-tos/store.md
> +On Node, the `FileLike` implementation is provided by the `@web-std/file` package, which is pulled in automatically when you add `web3.storage` to your project's dependencies. When running in the bro
> On Node

_In Node_? Or _Using Node_?

2021-07-08 16:25 UTC, johnnymatthews commented on docs/how-tos/store.md
> +```
````suggestion
Import the `File` object that matches your runtime platform.

- Node.js apps:

    ```javascript
    const { File } = require('@web-std/file')
    ```

- Browser-based apps:

    ```javascript
    const { File } = require('web3-file')
    ```
````

2021-07-08 16:25 UTC, johnnymatthews commented on docs/how-tos/store.md
> +```
````suggestion
:::tip Supporting both runtimes
If you're planning to support both runtimes, consider using a bundler like [webpack](https://webpack.js.org) or [rollup](https://rollupjs.org/guide/en/) that can selectively override imports based on the target platform. Then you can confine your platform-specific imports to one file, and the rest of your code can just do something like this:

```js
const { File } = require('./platform')
```
:::
````

2021-07-08 16:25 UTC, johnnymatthews commented on docs/how-tos/store.md
> +::: tip
```suggestion
::: tip Unique file names
```

2021-07-08 16:25 UTC, johnnymatthews commented on docs/how-tos/store.md
> +Try to give each file a unique file name! All the files in a `put` request will be bundled into one content archive, and linking to the files inside is much simpler if each file has a human-readable
```suggestion
Try to give each file a unique file name! All the files in a `put` request will be bundled into one content archive, and linking to the files inside is much simpler if each file has a unique human-readable name.
```

2021-07-08 16:25 UTC, johnnymatthews commented on docs/how-tos/store.md
> +The `name` parameter lets you attach an arbitrary name to the uploaded content archive, which you can use to identify and organize your uploads. The name is not stored alongside the data on IPFS, but
```suggestion
The `name` parameter lets you attach an arbitrary name to the uploaded content archive, which you can use to identify and organize your uploads. The name is not stored alongside the data on IPFS, but it is viewable within the [file listing][site-files] on the Web3.Storage site.
```

2021-07-08 16:25 UTC, johnnymatthews commented on docs/how-tos/store.md
> +The `put` method returns an [IPFS Content Identifier][ipfs-docs-cid] that can be used to fetch the files from IPFS. See the [retrieval how-to][howto-retrieve] to learn how to fetch your data using th
```suggestion
The `put` method returns an [IPFS Content Identifier][ipfs-docs-cid] that can be used to fetch the files from IPFS. See the [retrieval page][howto-retrieve] to learn how to fetch your data using the Web3.Storage client, or directly from IPFS using a gateway or the IPFS command line.
```

2021-07-08 16:25 UTC, johnnymatthews commented on docs/how-tos/store.md
> +You can also get more information about the status of your data. See the [query how-to][howto-query] to learn how to get more details about your data, including the status of any Filecoin storage dea
```suggestion
You can also get more information about the status of your data. See the [query page][howto-query] to learn how to get more details about your data, including the status of any Filecoin storage deals.
```

2021-07-08 16:42 UTC, johnnymatthews commented on docs/how-tos/retrieve.md
> +[ipfs-docs-cli-quickstart]: https://docs.ipfs.io/how-to/command-line-quick-start/
I kinda like the idea of having all the page links at the bottom of the page like this.

2021-07-08 21:49 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-tos/retrieve.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu/not-distributed.jpg
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...O: intro paragraph # Using an IPFS HTTP gateway You can easily fetch any dat...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ...is guide, we'll use the gateway at dweb.link, but you can check the list of ...
                                             ^^^^
  ```

2021-07-08 21:50 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-tos/retrieve.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu/not-distributed.jpg
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...O: intro paragraph # Using an IPFS HTTP gateway You can easily fetch any dat...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ...is guide, we'll use the gateway at dweb.link, but you can check the list of ...
                                             ^^^^
  ```

2021-07-08 21:50 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-tos/retrieve.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu/not-distributed.jpg
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...O: intro paragraph # Using an IPFS HTTP gateway You can easily fetch any dat...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ...is guide, we'll use the gateway at dweb.link, but you can check the list of ...
                                             ^^^^
  ```

2021-07-08 21:50 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-tos/retrieve.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu/not-distributed.jpg
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...O: intro paragraph # Using an IPFS HTTP gateway You can easily fetch any dat...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ...is guide, we'll use the gateway at dweb.link, but you can check the list of ...
                                             ^^^^
  ```

2021-07-08 21:50 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-tos/retrieve.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu/not-distributed.jpg
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...O: intro paragraph # Using an IPFS HTTP gateway You can easily fetch any dat...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ...is guide, we'll use the gateway at dweb.link, but you can check the list of ...
                                             ^^^^
  ```

2021-07-08 21:50 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-tos/retrieve.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu/not-distributed.jpg
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...O: intro paragraph # Using an IPFS HTTP gateway You can easily fetch any dat...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ...is guide, we'll use the gateway at dweb.link, but you can check the list of ...
                                             ^^^^
  ```

2021-07-08 21:50 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-tos/retrieve.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu/not-distributed.jpg
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...O: intro paragraph # Using an IPFS HTTP gateway You can easily fetch any dat...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ...is guide, we'll use the gateway at dweb.link, but you can check the list of ...
                                             ^^^^
  ```

2021-07-08 21:51 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-tos/retrieve.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu/not-distributed.jpg
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...O: intro paragraph # Using an IPFS HTTP gateway You can easily fetch any dat...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ...is guide, we'll use the gateway at dweb.link, but you can check the list of ...
                                             ^^^^
  ```

2021-07-08 21:59 UTC, yusefnapora commented on docs/how-tos/retrieve.md
> +TODO: intro paragraph
Yeah, just pushed up an intro. Thanks for catching all the TODO cruft I left in :)

2021-07-08 21:59 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-tos/retrieve.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu/not-distributed.jpg
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...ommand line tools. # Using an IPFS HTTP gateway You can easily fetch any dat...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ...is guide, we'll use the gateway at dweb.link, but you can check the list of ...
                                             ^^^^
  ```

2021-07-08 22:02 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-tos/retrieve.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu/not-distributed.jpg
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...eb3.Storage client # Using an IPFS HTTP gateway You can easily fetch any dat...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ...is guide, we'll use the gateway at dweb.link, but you can check the list of ...
                                             ^^^^
  ```

2021-07-08 22:02 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-tos/retrieve.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu/not-distributed.jpg
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...eb3.Storage client # Using an IPFS HTTP gateway You can easily fetch any dat...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ...is guide, we'll use the gateway at dweb.link, but you can check the list of ...
                                             ^^^^
  ```

2021-07-08 22:02 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-tos/retrieve.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu/not-distributed.jpg
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...eb3.Storage client # Using an IPFS HTTP gateway You can easily fetch any dat...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ...is guide, we'll use the gateway at dweb.link, but you can check the list of ...
                                             ^^^^
  ```

2021-07-08 22:03 UTC, yusefnapora commented on docs/how-tos/retrieve.md
> +[ipfs-docs-cli-quickstart]: https://docs.ipfs.io/how-to/command-line-quick-start/
I kind of like it too.. it makes the markdown text a bit easier to read IMO.  The only downside that I've found, apart from taking a few extra seconds vs inline links, is that sometimes I'll delete the link from the text but forget to remove the definition at the bottom. But that's invisible in the rendered output, so it just clutters up the source a bit and isn't a big deal.

2021-07-08 22:09 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-tos/retrieve.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu
- The following link returned HTTP status code 301 (Moved Permanently):
  https://dweb.link/ipfs/bafybeidd2gyhagleh47qeg77xqndy2qy3yzn4vkxmk775bg2t5lpuy7pcu/not-distributed.jpg
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...nd line tools. # Using the Web3.Storage client The Web3.Storage JavaScript c...
                                             ^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...t Identifier (CID)  (opens new window). First you'll need to create a Web3.S...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... you have a client, you can call client.get, passing in a CID string: # The ...
                                             ^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...to the retrieved IPFS data. # files The files method returns an array of Web...
                                             ^^^^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...g access to the retrieved data than the files method, at the cost of being a...
                                             ^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ... the iterator represent files. If entry.type == 'directory', the entry repre...
                                             ^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ... to other entries. # Using an IPFS HTTP gateway You can easily fetch any dat...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.<!--CategoryID:CASING, RuleID: LC_AFTER_PERIOD-->
  ```
  ...is guide, we'll use the gateway at dweb.link, but you can check the list of ...
                                             ^^^^
  ```

2021-07-09 03:54 UTC, johnnymatthews approved these changes

2021-07-09 14:28 UTC, merged